HTTP/1.1 200 OK
Server: llama.cpp
Access-Control-Allow-Origin: 
X-Accel-Buffering: no
Content-Type: text/event-stream
Transfer-Encoding: chunked
Connection: close

157
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"role":"assistant","content":null}}],"created":1790944240,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk","prompt_progress":{"total":383,"cache":330,"processed":330,"time_ms":77}}


159
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"role":"assistant","content":null}}],"created":1790944247,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk","prompt_progress":{"total":383,"cache":330,"processed":379,"time_ms":7799}}


159
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"role":"assistant","content":null}}],"created":1790944248,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk","prompt_progress":{"total":383,"cache":330,"processed":383,"time_ms":8402}}


20c
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"role":"assistant","content":null}}],"created":1790944248,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}

data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":"There"}}],"created":1790944248,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


fd
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":" are"}}],"created":1790944249,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


fc
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":" **"}}],"created":1790944249,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


fa
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":"1"}}],"created":1790944249,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


fa
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":"8"}}],"created":1790944249,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


fb
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":"**"}}],"created":1790944249,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


ff
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":" files"}}],"created":1790944249,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


fc
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":" in"}}],"created":1790944249,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


fd
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":" the"}}],"created":1790944249,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


101
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":" current"}}],"created":1790944250,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


103
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":" directory"}}],"created":1790944250,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


fa
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":"."}}],"created":1790944250,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}


350
data: {"choices":[{"finish_reason":"stop","index":0,"delta":{}}],"created":1790944250,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk"}

data: {"choices":[],"created":1790944250,"id":"chatcmpl-Sj59dU5YtO1rqbSTbFH7SprLdLIumCGr","model":"qwen3.8-flash-next","system_fingerprint":"b11102-e486f802d","object":"chat.completion.chunk","usage":{"completion_tokens":13,"prompt_tokens":383,"total_tokens":396,"prompt_tokens_details":{"cached_tokens":330}},"timings":{"cache_n":330,"prompt_n":53,"prompt_ms":8404.609,"prompt_per_token_ms":158.5775283018868,"prompt_per_second":6.306063732411585,"predicted_n":13,"predicted_ms":2224.04,"predicted_per_token_ms":185.33666666666667,"predicted_per_second":5.395586410316362,"draft_n":9,"draft_n_accepted":9}}


e
data: [DONE]


0

