//! `diet::seam` -- the render-and-ratify controller.
//!
//! Nothing else in this library owns the **render**: the moment the working
//! object is turned into a prompt and the session continues from it. That
//! moment is the architecture's single deliberate prefill event -- everything
//! else exists to make it rare, small and safe -- and it happens here and
//! nowhere else.
//!
//! Two things decide the design.
//!
//! **A seam fires on a deterministic trigger, never on the model's judgment.**
//! A declared cadence, a phase transition the graph ratified, or the working
//! set reaching a declared byte count. Who decides when to compact is the
//! metacognition problem this architecture refuses to hand to the model; the
//! answer is that the work has a shape and the shape decides. The model may
//! *propose* a phase transition, and [`phase::PhaseGraph`] rules on it -- an
//! unratified proposal is recorded and not acted on.
//!
//! **The prefix stays byte-identical between seams.** [`render::render`] is a
//! pure function of the object and the phase, and the controller re-runs it
//! only when a seam fires. That is what makes the claim checkable rather than
//! merely stated.
//!
//! # What is NOT built here, and why
//!
//! The ratification's *answer* is a format, and its grammar is not this
//! seat's to write. The dogma's audit asks want `KEEP` / `UPDATE` / `REMOVE`
//! / `ADD` back, ruling 1 on #25 put that vocabulary in `diet/formats/` as
//! its own verdict enum, and it is not implemented yet. Writing a second
//! parser for it here would be the eleven divergent decline-detectors again.
//!
//! So the controller takes a [`Ratifier`]: it builds the ask, hands over the
//! entries, and folds whatever patches come back. Everything the controller
//! owns -- the triggers, the render, the phase graph, the dumps either side,
//! the fold -- is built and tested. The parse is named as the dependency it
//! is.
//!
//! # What has been seen red
//!
//! **`diet/seam/gate.toml` is the list**, and it is generated by running
//! every entry: each fault is applied to the tree, this lane's tests are run,
//! and `catches` is what actually failed. Twenty-nine of them. The table used
//! to be restated here too, and a table restated in two places is a table
//! that goes stale in one of them.
//!
//! Three are worth naming, because each was a claim the suite could not
//! prove and two of them were found by somebody else looking.
//!
//! **Re-rendering the prefix on every turn changed no test.** Comparing
//! prefixes across turns while the object sits still proves nothing: the
//! render is a pure function, so re-running it on an unchanged object gives
//! the same bytes. The claim is not that the controller renders rarely -- it
//! is that the prefix does not move **while the object does**, and testing it
//! needs a lane writing every turn.
//!
//! **The phase and the pending triggers were committed above the fallible
//! steps.** A ratifier whose patches the reconciler refused left the
//! controller having advanced its phase and spent the operator's declaration
//! with no seam recorded -- rendering a prompt for the phase the session had
//! left. Nothing exercised the error path at all.
//!
//! **The render had no grammar.** Entry content reaches it from model output
//! through the capture lanes, and a note carrying a newline and a tab wrote a
//! whole extra working-set row into the next prefix with an id of the model's
//! choosing. [`render::one_line`] is the fix, and it is the same escaping the
//! audit ask needs so that `{n}` and the number of lines agree.

pub mod phase;
pub mod policy;
pub mod render;

use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fmt;

use crate::client::vocabulary;
use crate::dogma::{FillError, Hole, Template};
use crate::object::{Applied, EntryId, ObjectError, Patch, WorkingObject, changed_between};

use phase::{Decision, Proposal};
use policy::Policy;

vocabulary! {
    /// Why a seam fired.
    ///
    /// **Declaration order is precedence.** Where two triggers are true at
    /// once, the reason a record carries is the first of these, and the
    /// others are carried beside it rather than dropped -- a seam attributed
    /// to a cadence that would have fired on the budget anyway is a seam
    /// whose record answers the wrong question.
    ///
    /// An explicit act outranks every derived one, so the operator comes
    /// first. A phase transition outranks a budget because it changes what
    /// the prompt is FOR; a budget outranks a cadence because it is a limit
    /// and a cadence is a schedule.
    Reason {
        /// The operator declared a boundary. #27's vocabulary named three
        /// triggers and the dogma pins an ask for a fourth
        /// (`AUDIT_Q_HUMAN`); the issue was amended rather than the ask left
        /// unreachable.
        Operator => "operator",
        /// The phase graph ratified a transition.
        Phase => "phase",
        /// The working set reached the declared byte count.
        Budget => "budget",
        /// The declared cadence came round.
        Cadence => "cadence",
    }
}

vocabulary! {
    /// Why a seam rendered without a ratification.
    ///
    /// A seam still fires: the render is the point, and a prompt rebuilt
    /// without an audit is a prompt rebuilt. What does not happen is a fold,
    /// and the reason it did not is typed rather than absent.
    Blocked {
        /// The dogma pins no audit ask for this trigger. Dogma v1 has one for
        /// a phase boundary, one for a scheduled checkpoint and one for an
        /// operator-declared boundary; it has none for a budget threshold,
        /// and inventing the wording would be authoring dogma from a seat
        /// that does not own it.
        NoPinnedAsk => "no_pinned_ask",
        /// The working set is empty, so the audit would be a check of
        /// nothing, and a check of nothing is not a pass.
        NothingToAudit => "nothing_to_audit",
    }
}

/// Which category of working note the audit names.
///
/// One value, because [`crate::object::Entry`] has no slot: the dogma's asks
/// audit `constraints`, `gotchas`, `decisions`, `open_questions` and
/// `next_steps` separately, and the object does not know which an entry is.
/// Auditing everything under one heading is what this module can honestly do
/// today; per-slot asks need the object to carry the slot, which is
/// `diet/object/`'s to add.
pub const AUDIT_CATEGORY: &str = "working notes";

/// The ask a seam puts to the model, and what it is about.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Ask {
    /// Why the seam fired.
    pub reason: Reason,
    /// The pinned template the ask was built from.
    pub template: Template,
    /// The ask, filled.
    pub text: String,
    /// The entries handed over, in the order they are numbered in the ask.
    /// A [`Ratifier`]'s answer is per line, so the numbering has to be
    /// somewhere a caller can read rather than re-derive.
    pub items: Vec<EntryId>,
}

/// Something that can answer a seam's ask.
///
/// The trait exists because the answer's GRAMMAR is not this module's: see
/// the note at the top of the file. An implementation parses an answer into
/// patches; this module folds them and records what they moved.
pub trait Ratifier {
    /// The patches `ask`'s answer folds to.
    fn ratify(&mut self, ask: &Ask) -> Vec<Patch>;
}

/// What became of the ratification.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Ratification {
    /// The answer was folded through the reconciler.
    Folded {
        /// How many patches it produced.
        patches: usize,
    },
    /// No ask was put.
    Blocked(Blocked),
}

/// One seam: everything about the moment the prompt was rebuilt.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Seam {
    /// Its position in the session, from 1.
    pub index: u32,
    /// The turn it fired after.
    pub at_turn: u32,
    /// Why, in [`Reason`]'s precedence order.
    pub reason: Reason,
    /// Every other trigger that was also true, so a reader can tell a seam
    /// that would have fired anyway from one that would not.
    pub also: Vec<Reason>,
    /// The phase the render was built for.
    pub phase: Option<String>,
    /// The object, dumped before the fold.
    pub before: BTreeMap<EntryId, String>,
    /// The object, dumped after it.
    pub after: BTreeMap<EntryId, String>,
    /// Which entries the fold moved.
    pub moved: BTreeSet<EntryId>,
    /// What the ratification produced.
    pub patches: Vec<Patch>,
    /// What the reconciler did with each.
    pub applied: Vec<Applied>,
    /// Whether there was a ratification at all.
    pub ratified: Ratification,
    /// The prefix the session continues from.
    pub prefix: String,
    /// The working object's version after the fold. #27 asks for a
    /// *versioned* dump either side of a seam; the dumps themselves carry no
    /// header (it would appear in every diff), so the version is recorded
    /// here instead of being unrecoverable.
    pub object_version: u32,
    /// Which frame the prefix was built with. Until the maintainer authors
    /// the frame as dogma, this is [`render::FRAME_VERSION`] and a reader can
    /// tell these renders from renders under the authored one.
    pub frame_version: &'static str,
    /// What the working set measured when the seam fired.
    pub working_set_bytes: u64,
}

impl Seam {
    /// Whether the entries this seam's dumps differ on are exactly the ones
    /// its patches touched.
    ///
    /// The acceptance question for a seam, asked of the seam rather than
    /// reconstructed by a caller: a render that moved an entry no patch names
    /// is a render that edited the object, and the object is not the render's
    /// to edit.
    #[must_use]
    pub fn diff_is_exactly_the_patches(&self) -> bool {
        let touched: BTreeSet<EntryId> = self
            .applied
            .iter()
            .flat_map(Applied::touched)
            .filter(|id| self.before.get(id) != self.after.get(id))
            .collect();
        touched == self.moved
    }
}

/// Why a seam could not be taken.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SeamError {
    /// The reconciler refused the ratification's patches.
    Object(ObjectError),
    /// A pinned ask could not be filled, which is a defect in this module
    /// rather than anything a drive did.
    Fill(FillError),
}

impl fmt::Display for SeamError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Object(why) => write!(f, "the ratification did not apply: {why}"),
            Self::Fill(why) => write!(f, "the seam's ask could not be filled: {why}"),
        }
    }
}

impl Error for SeamError {}

impl From<ObjectError> for SeamError {
    fn from(why: ObjectError) -> Self {
        Self::Object(why)
    }
}

impl From<FillError> for SeamError {
    fn from(why: FillError) -> Self {
        Self::Fill(why)
    }
}

/// The controller.
#[derive(Debug, Clone)]
pub struct Controller<R: Ratifier> {
    policy: Policy,
    ratifier: R,
    phase: Option<String>,
    turn: u32,
    prefix: String,
    seams: Vec<Seam>,
    proposals: Vec<Proposal>,
    /// An operator-declared boundary, waiting for the turn to settle.
    ///
    /// Held rather than acted on for the same reason a ratified transition
    /// is: the turn it was declared in is still running.
    declared: bool,
    /// A transition the graph ratified, waiting for the turn to settle.
    ///
    /// A proposal does not fire a seam the instant it is made: the turn it
    /// was made in is still running, and rebuilding the prompt underneath it
    /// would be the controller acting on the model's judgment at the moment
    /// the model expressed it -- which is the thing the whole design refuses.
    pending: Option<String>,
}

impl<R: Ratifier> Controller<R> {
    /// A controller over `object`, under `policy`.
    ///
    /// The session starts in the graph's first phase, or in no phase where
    /// the graph is empty. The opening prefix is rendered here, so that the
    /// byte-identity claim covers the whole session and not only the part
    /// after the first seam.
    pub fn open(policy: Policy, object: &WorkingObject, ratifier: R) -> Self {
        let phase = policy.phases.first().map(str::to_owned);
        let prefix = render::render(object, phase.as_deref());
        Self {
            policy,
            ratifier,
            phase,
            turn: 0,
            prefix,
            seams: Vec::new(),
            proposals: Vec::new(),
            declared: false,
            pending: None,
        }
    }

    /// The prefix the session is continuing from.
    #[must_use]
    pub fn prefix(&self) -> &str {
        &self.prefix
    }

    /// The phase the session is in.
    #[must_use]
    pub fn phase(&self) -> Option<&str> {
        self.phase.as_deref()
    }

    /// Every seam so far.
    #[must_use]
    pub fn seams(&self) -> &[Seam] {
        &self.seams
    }

    /// The ratifier, so a caller can read what it was asked.
    ///
    /// The asks are the half of a seam that leaves this module, and a test
    /// that could not see them would be checking that the controller talks to
    /// itself.
    #[must_use]
    pub fn ratifier(&self) -> &R {
        &self.ratifier
    }

    /// Every proposal so far, ratified or not.
    #[must_use]
    pub fn proposals(&self) -> &[Proposal] {
        &self.proposals
    }

    /// Begin the next turn.
    pub fn begin_turn(&mut self) -> u32 {
        self.turn += 1;
        self.turn
    }

    /// Declare a boundary. The operator's own act, not the model's.
    ///
    /// No graph rules on it and nothing may refuse it: an operator saying
    /// "we are done with that part" is a fact, and a controller that asked a
    /// phase graph for permission would be treating a person as a proposal.
    /// It fires at the end of the turn it was declared in, like every other
    /// trigger.
    pub fn operator_declares_a_boundary(&mut self) {
        self.declared = true;
    }

    /// Record a phase transition the model proposed, and rule on it.
    ///
    /// The decision is returned AND recorded. A refused proposal fires
    /// nothing and changes nothing; it stays in [`Controller::proposals`],
    /// because the model believing the work had moved on is a fact about the
    /// drive and the one signal that says the graph and the work disagree.
    pub fn propose(&mut self, to: &str) -> Decision {
        let decision = self.policy.phases.decide(self.phase.as_deref(), to);
        if decision == Decision::Ratified {
            self.pending = Some(to.to_owned());
        }
        self.proposals.push(Proposal {
            at_turn: self.turn,
            from: self.phase.clone(),
            to: to.to_owned(),
            decision: decision.clone(),
        });
        decision
    }

    /// Settle the current turn: fire a seam if a trigger says to.
    ///
    /// # Errors
    ///
    /// Returns [`SeamError`] if the reconciler refuses the ratification's
    /// patches, or if a pinned ask could not be filled.
    pub fn settle(&mut self, object: &mut WorkingObject) -> Result<Option<Seam>, SeamError> {
        // One turn, one seam. A second `settle` in the same turn used to fire
        // a second one at the same index -- two full re-prefills for a turn
        // that only ever had one prompt to rebuild.
        if self
            .seams
            .last()
            .is_some_and(|seam| seam.at_turn == self.turn)
        {
            return Ok(None);
        }

        let working_set_bytes = render::working_set_bytes(object);
        let reasons = self.triggers(working_set_bytes);
        let Some(&reason) = reasons.first() else {
            return Ok(None);
        };

        // NOTHING is committed until both fallible steps are through.
        //
        // The phase used to be taken and the pending triggers cleared right
        // here, above the `?`s below -- so a ratifier whose patches the
        // reconciler refused left the controller having advanced its phase,
        // spent the operator's declaration, and recorded no seam. The prefix
        // still rendered the phase the session had left, which is the exact
        // failure the byte-identity design exists to prevent, and the
        // declared boundary never happened at all. The `Ratifier` is the seam
        // to model output, so that is not a rare path.
        let taking = self.pending.clone();
        let phase = taking.clone().or_else(|| self.phase.clone());

        let before = object.dump_lines();
        let (ratified, patches) = self.audit(object, reason)?;
        let applied = object.apply_turn(&patches)?;
        let after = object.dump_lines();
        let moved = changed_between(&before, &after);

        // Past the last `?`. Commit.
        if let Some(to) = taking {
            self.phase = Some(to);
        }
        self.pending = None;
        self.declared = false;
        self.prefix = render::render(object, phase.as_deref());

        let index = u32::try_from(self.seams.len()).unwrap_or(u32::MAX) + 1;
        let seam = Seam {
            index,
            at_turn: self.turn,
            reason,
            also: reasons[1..].to_vec(),
            phase,
            before,
            after,
            moved,
            patches,
            applied,
            ratified,
            prefix: self.prefix.clone(),
            frame_version: render::FRAME_VERSION,
            object_version: object.version(),
            working_set_bytes,
        };
        self.seams.push(seam.clone());
        Ok(Some(seam))
    }

    /// Every trigger that is true right now, in precedence order.
    fn triggers(&self, working_set_bytes: u64) -> Vec<Reason> {
        Reason::ALL
            .iter()
            .copied()
            .filter(|reason| match reason {
                Reason::Operator => self.declared,
                Reason::Phase => self.pending.is_some(),
                Reason::Budget => self
                    .policy
                    .at_working_set_bytes
                    .is_some_and(|at| working_set_bytes >= at),
                // `turn > 0` because turn zero is before the session started,
                // and every number divides zero: without it a controller that
                // settled before its first turn would fire a seam over an
                // empty object.
                Reason::Cadence => self
                    .policy
                    .every_turns
                    .is_some_and(|every| self.turn > 0 && self.turn.is_multiple_of(every)),
            })
            .collect()
    }

    /// Put the audit to the ratifier, or say why it was not put.
    fn audit(
        &mut self,
        object: &WorkingObject,
        reason: Reason,
    ) -> Result<(Ratification, Vec<Patch>), SeamError> {
        let Some(template) = pinned_ask(reason) else {
            return Ok((Ratification::Blocked(Blocked::NoPinnedAsk), Vec::new()));
        };

        let items: Vec<(EntryId, String)> = object
            .live()
            .map(|entry| (entry.id.clone(), entry.content.clone()))
            .collect();
        if items.is_empty() {
            return Ok((Ratification::Blocked(Blocked::NothingToAudit), Vec::new()));
        }

        let numbered = items
            .iter()
            .enumerate()
            .map(|(index, (_, content))| format!("{}. {}", index + 1, render::one_line(content)))
            .collect::<Vec<_>>()
            .join("\n");
        let count = items.len().to_string();
        let text = template.fill(&[
            (Hole::Category, AUDIT_CATEGORY),
            (Hole::LineCount, &count),
            (Hole::Items, &numbered),
        ])?;

        let ask = Ask {
            reason,
            template,
            text,
            items: items.into_iter().map(|(id, _)| id).collect(),
        };
        let patches = self.ratifier.ratify(&ask);
        Ok((
            Ratification::Folded {
                patches: patches.len(),
            },
            patches,
        ))
    }
}

/// The dogma's audit ask for a trigger, where one is pinned.
///
/// A table rather than a guess. The dogma pins an ask for a phase boundary
/// and one for a scheduled checkpoint, and it pins none for a budget
/// threshold: `AUDIT_Q_CADENCE`'s own text says "a cadence fired", so
/// borrowing it for a budget seam would put a sentence in the prompt that is
/// not true. Writing a new one is authoring dogma, which is not this seat's.
#[must_use]
pub fn pinned_ask(reason: Reason) -> Option<Template> {
    match reason {
        Reason::Operator => Some(Template::AuditQHuman),
        Reason::Phase => Some(Template::AuditQ),
        Reason::Cadence => Some(Template::AuditQCadence),
        Reason::Budget => None,
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::phase::{Decision, Refusal};
    use super::policy::{Policy, PolicyError};
    use super::{
        Ask, Blocked, Controller, Ratification, Ratifier, Reason, Seam, SeamError, pinned_ask,
        render,
    };
    use crate::formats::record::{Reasoning, Regime, Substrate};
    use crate::formats::regimen;
    use crate::object::{EntryId, Patch, Provenance, WorkingObject};

    fn regime() -> Regime {
        Regime {
            arm: "an-arm".to_owned(),
            substrate: Substrate {
                name: "a-substrate".to_owned(),
                model: "a-model".to_owned(),
                quantization: "q8".to_owned(),
                sampler: BTreeMap::new(),
                reasoning: Reasoning::Off,
                hardware: "a-box".to_owned(),
            },
            dogma_version: 1,
        }
    }

    fn id(text: &str) -> EntryId {
        EntryId::new(text).expect("a non-blank id")
    }

    fn provenance(turn: u32, index: u32) -> Provenance {
        Provenance {
            turn,
            lane: "ratify".to_owned(),
            fork: None,
            tangent: None,
            index,
        }
    }

    fn add(name: &str, content: &str, turn: u32, index: u32) -> Patch {
        Patch::Add {
            id: id(name),
            content: content.to_owned(),
            provenance: provenance(turn, index),
        }
    }

    /// An object with three live entries, so an audit has something to audit.
    fn three_facts() -> WorkingObject {
        let mut object = WorkingObject::open(regime());
        object
            .apply_turn(&[
                add("e1", "the parser refuses a bare tilde", 1, 0),
                add("e2", "the gate runs on every invocation", 1, 1),
                add("e3", "the register is mined, not authored", 1, 2),
            ])
            .expect("three adds apply");
        object
    }

    fn policy(text: &str) -> Policy {
        Policy::from_regimen(&regimen::parse(text).expect("a regimen")).expect("a policy")
    }

    /// A ratifier that answers from a script and keeps what it was asked.
    #[derive(Debug, Clone, Default)]
    struct Scripted {
        give: Vec<Vec<Patch>>,
        seen: Vec<Ask>,
    }

    impl Scripted {
        fn silent() -> Self {
            Self::default()
        }

        fn answering(give: Vec<Vec<Patch>>) -> Self {
            Self {
                give,
                seen: Vec::new(),
            }
        }
    }

    impl Ratifier for Scripted {
        fn ratify(&mut self, ask: &Ask) -> Vec<Patch> {
            self.seen.push(ask.clone());
            if self.give.is_empty() {
                Vec::new()
            } else {
                self.give.remove(0)
            }
        }
    }

    /// Drive `turns` turns, settling each, and return the prefix after each.
    fn drive(
        controller: &mut Controller<Scripted>,
        object: &mut WorkingObject,
        turns: u32,
    ) -> Vec<String> {
        let mut prefixes = Vec::new();
        for _ in 0..turns {
            controller.begin_turn();
            controller.settle(object).expect("the fold applies");
            prefixes.push(controller.prefix().to_owned());
        }
        prefixes
    }

    // -----------------------------------------------------------------------
    // #27's acceptance rows
    // -----------------------------------------------------------------------

    /// Row two, both readings. The issue says "five turns at
    /// `seam_every_turns = 3`" and then "seams fire at turns 3 and 6 only",
    /// and a five-turn drive has no turn 6. Rather than pick one, this asserts
    /// both: seven turns fire at 3 and 6, five turns fire at 3 alone. The
    /// discrepancy is disclosed on the pull request.
    #[test]
    fn seams_fire_on_the_declared_cadence_and_nowhere_else() {
        let mut object = three_facts();
        let mut controller = Controller::open(
            policy("seam_every_turns = 3\n"),
            &object,
            Scripted::silent(),
        );
        drive(&mut controller, &mut object, 7);

        let fired: Vec<(u32, Reason)> = controller
            .seams()
            .iter()
            .map(|seam| (seam.at_turn, seam.reason))
            .collect();
        assert_eq!(
            fired,
            vec![(3, Reason::Cadence), (6, Reason::Cadence)],
            "turns 3 and 6, and no others, each because the cadence came round"
        );
        assert!(
            controller.seams().iter().all(|seam| seam.also.is_empty()),
            "no other trigger was declared, so none can also have been true"
        );
        assert_eq!(Reason::Cadence.tag(), "cadence");

        let mut short_object = three_facts();
        let mut short = Controller::open(
            policy("seam_every_turns = 3\n"),
            &short_object,
            Scripted::silent(),
        );
        drive(&mut short, &mut short_object, 5);
        assert_eq!(
            short
                .seams()
                .iter()
                .map(|seam| seam.at_turn)
                .collect::<Vec<_>>(),
            vec![3],
            "five turns reach turn 3 and not turn 6"
        );
    }

    /// Row two's other half: the prefix between seams is byte-identical.
    #[test]
    fn the_prefix_is_byte_identical_between_seams_and_changes_only_at_one() {
        let mut object = three_facts();
        let mut controller = Controller::open(
            policy("seam_every_turns = 3\n"),
            &object,
            // A seam that folds a patch, so the render has something to
            // change. A prefix that never moved would make this test pass on
            // a controller that never rendered at all.
            Scripted::answering(vec![vec![add("e4", "and a fourth fact", 3, 0)]]),
        );
        let opening = controller.prefix().to_owned();
        let prefixes = drive(&mut controller, &mut object, 5);

        assert_eq!(
            prefixes[0], opening,
            "turn 1 continues from the opening prefix"
        );
        assert_eq!(prefixes[1], opening, "so does turn 2");
        assert_ne!(
            prefixes[2], opening,
            "the seam at turn 3 rebuilt it, or nothing here is being measured"
        );
        assert_eq!(
            prefixes[3], prefixes[2],
            "and turn 4 continues from the new one"
        );
        assert_eq!(prefixes[4], prefixes[2], "and so does turn 5");
        assert!(
            prefixes[2].contains("and a fourth fact"),
            "the new prefix carries what the ratification added: {}",
            prefixes[2]
        );
    }

    /// The claim #27 exists for, and the one the test above could not make.
    ///
    /// Comparing prefixes across turns while the object sits still proves
    /// nothing: re-rendering every turn from an unchanged object produces the
    /// same bytes, and mutating the controller to do exactly that left the
    /// whole suite green. The claim is not that the controller renders
    /// rarely -- it is that **the prefix does not move while the object
    /// does**. A capture lane writes on every turn; a controller that
    /// rendered mid-phase would change the prefix under a warm cache and pay
    /// a full re-prefill for each of those turns.
    #[test]
    fn the_prefix_does_not_move_while_the_object_does() {
        let mut object = three_facts();
        let mut controller = Controller::open(
            policy("seam_every_turns = 3\n"),
            &object,
            Scripted::silent(),
        );
        let opening = controller.prefix().to_owned();
        let mut prefixes = Vec::new();

        for turn in 1..=5_u32 {
            controller.begin_turn();
            // A lane writes a fact, as one does every turn.
            object
                .apply_turn(&[add(
                    &format!("lane-{turn}"),
                    &format!("a fact captured on turn {turn}"),
                    turn,
                    0,
                )])
                .expect("the lane's patch applies");
            controller.settle(&mut object).expect("the fold applies");
            prefixes.push(controller.prefix().to_owned());
        }

        assert_eq!(
            prefixes[0], opening,
            "turn 1 wrote to the object and the prefix did not move"
        );
        assert_eq!(prefixes[1], opening, "nor on turn 2");
        assert!(
            !opening.contains("a fact captured on turn 1"),
            "and the prefix genuinely lags the object: the lane's fact is in the \
             object and not yet in the prompt"
        );

        assert_ne!(prefixes[2], opening, "the seam at turn 3 rebuilt it");
        assert!(
            prefixes[2].contains("a fact captured on turn 1")
                && prefixes[2].contains("a fact captured on turn 3"),
            "and picked up everything the lanes wrote in between: {}",
            prefixes[2]
        );

        assert_eq!(
            prefixes[3], prefixes[2],
            "turn 4 wrote, and the prefix held"
        );
        assert_eq!(prefixes[4], prefixes[2], "and so did turn 5");
        assert!(
            !prefixes[4].contains("a fact captured on turn 4"),
            "which is the whole claim: the object has moved on and the prompt has not"
        );
    }

    /// Row three: a proposal the graph forbids is recorded, and no seam fires.
    #[test]
    fn a_transition_the_graph_forbids_is_recorded_and_fires_nothing() {
        let declared = "phases = [\"brainstorm\", \"plan\", \"implement\"]\n\
                        [phase_transitions]\n\
                        brainstorm = [\"plan\"]\n\
                        plan = [\"implement\"]\n";
        let mut object = three_facts();
        let mut controller = Controller::open(policy(declared), &object, Scripted::silent());

        controller.begin_turn();
        let decision = controller.propose("implement");
        assert_eq!(
            decision,
            Decision::Refused(Refusal::NoEdge),
            "brainstorm reaches plan, and plan reaches implement; nothing skips"
        );
        assert!(
            controller
                .settle(&mut object)
                .expect("nothing to fold")
                .is_none(),
            "an unratified proposal is recorded, not acted on"
        );

        let proposals = controller.proposals();
        assert_eq!(proposals.len(), 1);
        assert_eq!(proposals[0].at_turn, 1);
        assert_eq!(proposals[0].from.as_deref(), Some("brainstorm"));
        assert_eq!(proposals[0].to, "implement");
        assert_eq!(proposals[0].decision, Decision::Refused(Refusal::NoEdge));
        assert_eq!(
            controller.phase(),
            Some("brainstorm"),
            "and the session did not move"
        );
        assert!(controller.seams().is_empty());
    }

    #[test]
    fn a_name_that_is_not_a_phase_is_refused_differently_from_one_that_is() {
        let declared = "phases = [\"plan\", \"implement\"]\n\
                        [phase_transitions]\n\
                        plan = [\"implement\"]\n";
        let mut object = three_facts();
        let mut controller = Controller::open(policy(declared), &object, Scripted::silent());

        controller.begin_turn();
        assert_eq!(
            controller.propose("ship"),
            Decision::Refused(Refusal::NotAPhase),
            "a phase that does not exist and a move the graph forbids are \
             different facts about a drive"
        );
        assert_eq!(
            controller.propose("plan"),
            Decision::Refused(Refusal::AlreadyThere),
            "and so is proposing the phase the session is already in"
        );
        assert_eq!(controller.proposals().len(), 2);
        assert!(
            controller
                .settle(&mut object)
                .expect("nothing folds")
                .is_none()
        );
    }

    #[test]
    fn a_transition_the_graph_allows_fires_a_seam_whose_reason_is_the_phase() {
        let declared = "phases = [\"plan\", \"implement\"]\n\
                        [phase_transitions]\n\
                        plan = [\"implement\"]\n";
        let mut object = three_facts();
        let mut controller = Controller::open(policy(declared), &object, Scripted::silent());

        controller.begin_turn();
        assert_eq!(controller.propose("implement"), Decision::Ratified);
        let seam = controller
            .settle(&mut object)
            .expect("the fold applies")
            .expect("a ratified transition fires a seam");

        assert_eq!(seam.reason, Reason::Phase);
        assert_eq!(seam.phase.as_deref(), Some("implement"));
        assert_eq!(controller.phase(), Some("implement"));
        assert!(
            seam.prefix.contains("phase: implement"),
            "and the new prompt is built for the new phase: {}",
            seam.prefix
        );
        assert_eq!(
            seam.ratified,
            Ratification::Folded { patches: 0 },
            "a phase boundary has a pinned ask, and this ratifier had nothing to say"
        );
    }

    /// Row four: the dumps either side of a seam differ by exactly the
    /// ratification's patches.
    #[test]
    fn the_dumps_either_side_of_a_seam_differ_by_exactly_the_ratifications_patches() {
        let mut object = three_facts();
        let mut controller = Controller::open(
            policy("seam_every_turns = 1\n"),
            &object,
            Scripted::answering(vec![
                vec![add("e4", "a fact the audit added", 1, 0)],
                vec![Patch::Supersede {
                    id: id("e5"),
                    content: "the parser refuses a bare tilde only in command position".to_owned(),
                    voids: id("e1"),
                    provenance: provenance(2, 0),
                }],
            ]),
        );

        for expected in [1_usize, 2] {
            controller.begin_turn();
            let seam = controller
                .settle(&mut object)
                .expect("the fold applies")
                .expect("a seam every turn");
            assert!(
                seam.diff_is_exactly_the_patches(),
                "seam {} moved {:?}, and its patches touched something else",
                seam.index,
                seam.moved
            );
            assert!(
                !seam.moved.is_empty(),
                "a seam whose dumps are identical proves nothing about attribution"
            );
            assert_eq!(seam.patches.len(), 1);
            assert_eq!(seam.index, u32::try_from(expected).expect("small"));
        }

        // The supersede: the voided entry is still there, linked, and the
        // diff names both it and its replacement.
        let last = controller.seams().last().expect("two seams");
        assert!(last.moved.contains(&id("e1")), "the voided entry moved");
        assert!(last.moved.contains(&id("e5")), "and so did its replacement");
        assert!(
            last.before.contains_key(&id("e1")) && last.after.contains_key(&id("e1")),
            "and it was voided, not removed"
        );
    }

    // -----------------------------------------------------------------------
    // the rest of the controller
    // -----------------------------------------------------------------------

    #[test]
    fn a_regimen_that_declares_no_trigger_never_fires_a_seam() {
        // The scale-adaptive case: forcing a three-phase ceremony onto a
        // one-line change is the known rigidity cost, so a regimen may decline
        // the whole apparatus by saying nothing.
        let empty = policy("model = \"a-model\"\n");
        assert!(!empty.declares_a_trigger());

        let mut object = three_facts();
        let mut controller = Controller::open(empty, &object, Scripted::silent());
        let opening = controller.prefix().to_owned();
        let prefixes = drive(&mut controller, &mut object, 9);

        assert!(controller.seams().is_empty(), "nine turns, no seam");
        assert!(
            prefixes.iter().all(|prefix| *prefix == opening),
            "and one prefix throughout"
        );
        assert_eq!(controller.phase(), None);
    }

    #[test]
    fn a_budget_seam_renders_and_says_no_ask_is_pinned_for_it() {
        let mut object = three_facts();
        let bytes = render::working_set_bytes(&object);
        let mut controller = Controller::open(
            policy(&format!("seam_at_working_set_bytes = {bytes}\n")),
            &object,
            Scripted::silent(),
        );

        controller.begin_turn();
        let seam = controller
            .settle(&mut object)
            .expect("nothing folds")
            .expect("the working set reached the declared count");

        assert_eq!(seam.reason, Reason::Budget);
        assert_eq!(seam.working_set_bytes, bytes);
        assert_eq!(
            seam.ratified,
            Ratification::Blocked(Blocked::NoPinnedAsk),
            "dogma v1 pins an ask for a phase boundary and one for a cadence, and \
             none for a budget; borrowing the cadence's would put a sentence in the \
             prompt that is not true"
        );
        assert!(pinned_ask(Reason::Budget).is_none());
        assert!(controller.ratifier().seen.is_empty(), "nothing was asked");
        assert!(
            !seam.prefix.is_empty(),
            "the render still happened -- the render is the point"
        );
    }

    #[test]
    fn a_phase_transition_outranks_a_cadence_that_also_came_round() {
        let declared = "seam_every_turns = 1\n\
                        phases = [\"plan\", \"implement\"]\n\
                        [phase_transitions]\n\
                        plan = [\"implement\"]\n";
        let mut object = three_facts();
        let mut controller = Controller::open(policy(declared), &object, Scripted::silent());

        controller.begin_turn();
        assert_eq!(controller.propose("implement"), Decision::Ratified);
        let seam = controller
            .settle(&mut object)
            .expect("the fold applies")
            .expect("both triggers are true");

        assert_eq!(
            seam.reason,
            Reason::Phase,
            "the stronger reason is the record's"
        );
        assert_eq!(
            seam.also,
            vec![Reason::Cadence],
            "and the one it outranked is beside it, not dropped: a seam that would \
             have fired anyway is a different fact from one that would not"
        );
    }

    #[test]
    fn an_operator_declared_boundary_outranks_every_derived_trigger() {
        // All four true at once. An operator saying "we are done with that
        // part" is a fact, not a proposal: no graph rules on it and nothing
        // may refuse it.
        let declared = "seam_every_turns = 1\n\
                        seam_at_working_set_bytes = 1\n\
                        phases = [\"plan\", \"implement\"]\n\
                        [phase_transitions]\n\
                        plan = [\"implement\"]\n";
        let mut object = three_facts();
        let mut controller = Controller::open(policy(declared), &object, Scripted::silent());

        controller.begin_turn();
        assert_eq!(controller.propose("implement"), Decision::Ratified);
        controller.operator_declares_a_boundary();
        let seam = controller
            .settle(&mut object)
            .expect("the fold applies")
            .expect("four triggers, one seam");

        assert_eq!(seam.reason, Reason::Operator);
        assert_eq!(
            seam.also,
            vec![Reason::Phase, Reason::Budget, Reason::Cadence],
            "and the three it outranked are beside it, in precedence order"
        );
        assert_eq!(
            controller.phase(),
            Some("implement"),
            "a transition the graph already allowed is not discarded because a \
             stronger trigger fired in the same turn"
        );
        assert_eq!(
            seam.ratified,
            Ratification::Folded { patches: 0 },
            "and the operator's boundary has a pinned ask of its own"
        );
    }

    #[test]
    fn an_operator_declared_boundary_fires_once() {
        let mut object = three_facts();
        let mut controller =
            Controller::open(policy("model = \"a-model\"\n"), &object, Scripted::silent());

        controller.begin_turn();
        controller.operator_declares_a_boundary();
        assert!(
            controller
                .settle(&mut object)
                .expect("nothing folds")
                .is_some(),
            "a declaration fires a seam even where the regimen declares no trigger"
        );

        controller.begin_turn();
        assert!(
            controller
                .settle(&mut object)
                .expect("nothing folds")
                .is_none(),
            "an operator who said `now` did not say `and again`"
        );
        assert_eq!(controller.seams().len(), 1);
    }

    #[test]
    fn an_operator_seam_puts_the_ask_the_dogma_pins_for_one() {
        let mut object = three_facts();
        let mut controller =
            Controller::open(policy("model = \"a-model\"\n"), &object, Scripted::silent());
        controller.begin_turn();
        controller.operator_declares_a_boundary();
        controller.settle(&mut object).expect("nothing folds");

        let seen = &controller.ratifier().seen;
        assert_eq!(seen.len(), 1);
        assert_eq!(seen[0].template, crate::dogma::Template::AuditQHuman);
        assert_eq!(
            pinned_ask(Reason::Operator),
            Some(crate::dogma::Template::AuditQHuman)
        );
        assert!(
            seen[0].text.contains("the operator declared one"),
            "the dogma's own words for this boundary, not the cadence's: {}",
            seen[0].text
        );
    }

    #[test]
    fn the_render_names_the_frame_it_was_built_with() {
        // The frame is prompt text and prompt text is judgment-as-data, so it
        // belongs to the maintainer. Until it is authored, a drive under this
        // one has to be distinguishable from a drive under that one, or the
        // two get compared as though they were the same regime.
        let object = three_facts();
        assert!(
            render::render(&object, None).contains("frame_version: placeholder"),
            "the prompt says which frame built it"
        );
        assert_eq!(render::FRAME_VERSION, "placeholder");

        let mut object = object;
        let mut controller = Controller::open(
            policy("seam_every_turns = 1\n"),
            &object,
            Scripted::silent(),
        );
        controller.begin_turn();
        let seam = controller
            .settle(&mut object)
            .expect("nothing folds")
            .expect("a seam");
        assert_eq!(
            seam.frame_version, "placeholder",
            "and so does the record of it"
        );
    }

    #[test]
    fn an_empty_working_set_is_not_audited() {
        let mut object = WorkingObject::open(regime());
        let mut controller = Controller::open(
            policy("seam_every_turns = 1\n"),
            &object,
            Scripted::silent(),
        );

        controller.begin_turn();
        let seam = controller
            .settle(&mut object)
            .expect("nothing folds")
            .expect("the cadence came round");

        assert_eq!(
            seam.ratified,
            Ratification::Blocked(Blocked::NothingToAudit),
            "a check of nothing is not a pass"
        );
        assert!(controller.ratifier().seen.is_empty());
    }

    #[test]
    fn the_ask_is_the_pinned_dogma_template_filled_with_the_live_entries() {
        let mut object = three_facts();
        let mut controller = Controller::open(
            policy("seam_every_turns = 1\n"),
            &object,
            Scripted::silent(),
        );
        controller.begin_turn();
        controller.settle(&mut object).expect("nothing folds");

        let seen = &controller.ratifier().seen;
        assert_eq!(seen.len(), 1, "one seam, one ask");
        let ask = &seen[0];
        assert_eq!(ask.template, crate::dogma::Template::AuditQCadence);
        assert_eq!(ask.reason, Reason::Cadence);
        assert_eq!(
            ask.items,
            vec![id("e1"), id("e2"), id("e3")],
            "the numbering the answer will refer to is on the ask, not re-derived"
        );
        assert!(
            ask.text.contains("1. the parser refuses a bare tilde"),
            "the entries are numbered from one: {}",
            ask.text
        );
        assert!(ask.text.contains("3. the register is mined, not authored"));
        assert!(
            ask.text.contains("scheduled checkpoint"),
            "and the wording is the dogma's, for the trigger that fired: {}",
            ask.text
        );
        assert!(
            !ask.text.contains("{items}") && !ask.text.contains("{n}"),
            "every hole is filled"
        );
    }

    /// Every fault in this lane's `gate.toml` still names source that exists.
    ///
    /// The manifest carries each mutation's exact source text so the
    /// orchestrator (#46) can apply it. That only works while the text is
    /// still in the file it names, and nothing else checks: the orchestrator
    /// is not built, and `check-fault-manifest.py` reads the gate's own
    /// manifest rather than a package's. A manifest nobody checks is a
    /// manifest that goes stale, and a stale seeded fault is one that
    /// silently stops testing what it says it tests.
    ///
    /// Scanned rather than parsed as TOML: this crate has no TOML reader for
    /// multi-line strings, and writing one to check a file this repository
    /// generates would be a second reader of a format that already has one.
    /// The scan mirrors the generator's shape exactly, and a scan that finds
    /// no faults fails rather than passing over nothing.
    #[test]
    fn every_seeded_fault_still_names_source_that_is_there() {
        crate::gate::every_seeded_fault_still_names_source(
            include_str!("../../seam/gate.toml"),
            // The lane's whole source, so a catcher can be looked for
            // wherever its test lives rather than only in this file.
            concat!(include_str!("mod.rs")),
            "seam",
        );
    }

    /// A ratifier whose patches the reconciler will refuse.
    ///
    /// Two patches from different turns. The `Ratifier` is this module's seam
    /// to model output, so an answer the reconciler will not take is the
    /// ordinary case rather than a strange one.
    #[derive(Debug, Clone)]
    struct Refused;

    impl Ratifier for Refused {
        fn ratify(&mut self, _ask: &Ask) -> Vec<Patch> {
            vec![add("z1", "one", 1, 0), add("z2", "two", 2, 0)]
        }
    }

    #[test]
    fn a_refused_fold_leaves_the_controller_exactly_where_it_was() {
        // The phase and the pending triggers used to be committed ABOVE the
        // two fallible steps, so a refused fold left the controller having
        // advanced its phase, spent the operator's declaration, and recorded
        // no seam -- with the prefix still rendering the phase the session had
        // left. That is the failure the byte-identity design exists to
        // prevent, produced by the controller itself.
        let declared = "phases = [\"plan\", \"implement\"]\n\
                        [phase_transitions]\n\
                        plan = [\"implement\"]\n";
        let mut object = three_facts();
        let mut controller = Controller::open(policy(declared), &object, Refused);
        let opening = controller.prefix().to_owned();

        controller.begin_turn();
        assert_eq!(controller.propose("implement"), Decision::Ratified);
        controller.operator_declares_a_boundary();
        let refused = controller
            .settle(&mut object)
            .expect_err("the fold is refused");
        assert!(matches!(refused, SeamError::Object(_)), "{refused:?}");

        assert!(controller.seams().is_empty(), "no seam was recorded");
        assert_eq!(
            controller.phase(),
            Some("plan"),
            "so the session did not advance"
        );
        assert_eq!(
            controller.prefix(),
            opening,
            "and the prompt still describes where it actually is"
        );

        // And the triggers were not spent by a seam that did not happen.
        let mut object = three_facts();
        let mut controller = Controller::open(policy(declared), &object, Scripted::silent());
        controller.begin_turn();
        assert_eq!(controller.propose("implement"), Decision::Ratified);
        controller.operator_declares_a_boundary();
        let seam = controller
            .settle(&mut object)
            .expect("this ratifier's answer applies")
            .expect("the declared boundary still fires");
        assert_eq!(seam.reason, Reason::Operator);
        assert_eq!(controller.phase(), Some("implement"));
    }

    #[test]
    fn a_seam_whose_dumps_moved_an_entry_no_patch_names_is_not_exactly_the_patches() {
        // The predicate acceptance row four turns on had only ever been
        // asserted TRUE, so replacing its body with `true` left the suite
        // green. This is the other side.
        let mut object = three_facts();
        let mut controller = Controller::open(
            policy("seam_every_turns = 1\n"),
            &object,
            Scripted::answering(vec![vec![add("e4", "a fact the audit added", 1, 0)]]),
        );
        controller.begin_turn();
        let honest = controller
            .settle(&mut object)
            .expect("the fold applies")
            .expect("a seam");
        assert!(honest.diff_is_exactly_the_patches());

        let forged = Seam {
            moved: honest
                .moved
                .iter()
                .cloned()
                .chain(std::iter::once(id("e1")))
                .collect(),
            ..honest.clone()
        };
        assert!(
            !forged.diff_is_exactly_the_patches(),
            "an entry the dumps moved that no patch touched is the render editing \
             the object, and the object is not the render's to edit"
        );
    }

    #[test]
    fn a_phase_boundary_gets_the_phase_boundarys_ask() {
        // The module's argument is that borrowing an ask puts a sentence in
        // the prompt that is not true. It was asserted for the budget and the
        // operator and not for the phase -- the trigger #27 names first.
        let declared = "phases = [\"plan\", \"implement\"]\n\
                        [phase_transitions]\n\
                        plan = [\"implement\"]\n";
        let mut object = three_facts();
        let mut controller = Controller::open(policy(declared), &object, Scripted::silent());
        controller.begin_turn();
        assert_eq!(controller.propose("implement"), Decision::Ratified);
        controller.settle(&mut object).expect("the fold applies");

        let seen = &controller.ratifier().seen;
        assert_eq!(seen.len(), 1);
        assert_eq!(seen[0].template, crate::dogma::Template::AuditQ);
        assert_eq!(
            pinned_ask(Reason::Phase),
            Some(crate::dogma::Template::AuditQ)
        );
        assert!(
            !seen[0].text.contains("a cadence fired"),
            "a phase boundary is not a scheduled checkpoint, and the ask must not \
             say it is: {}",
            seen[0].text
        );
    }

    #[test]
    fn the_working_set_measures_exactly_what_the_render_emits() {
        // `> 0` and `< the whole render` are both true of a measurement that
        // is off by any proportion, because the render carries a regime header
        // worth a hundred bytes of slack. This is the binding form.
        for object in [three_facts(), WorkingObject::open(regime())] {
            let rendered = render::render(&object, Some("plan"));
            let (_, working_set) = rendered
                .split_once(render::WORKING_SET_HEADER)
                .expect("the render has a working set");
            assert_eq!(
                render::working_set_bytes(&object),
                working_set.len() as u64,
                "the trigger measures the bytes that are actually sent"
            );
        }
    }

    #[test]
    fn the_render_is_injective_so_one_entry_cannot_forge_a_row() {
        // Entry content comes from model output through the capture lanes. A
        // note carrying a newline, a tab and an id of the model's choosing
        // used to place a whole extra working-set row into the next prefix --
        // and made two different objects render to the same bytes, which is
        // the byte-identity claim holed in the other direction.
        let mut two = WorkingObject::open(regime());
        two.apply_turn(&[add("a", "x", 1, 0), add("b", "y", 1, 1)])
            .expect("two adds apply");
        let mut one = WorkingObject::open(regime());
        one.apply_turn(&[add("a", "x\nb\ty", 1, 0)])
            .expect("one add applies");

        assert_eq!(one.live().count(), 1);
        assert_eq!(two.live().count(), 2);
        assert_ne!(
            render::render(&two, None),
            render::render(&one, None),
            "two objects, two prompts"
        );
        assert!(
            render::render(&one, None).contains("a\tx\\nb\\ty\n"),
            "and the forged row is one escaped row: {}",
            render::render(&one, None)
        );
    }

    #[test]
    fn an_entry_with_a_newline_is_still_one_numbered_line_in_the_ask() {
        // All three pinned asks say "reply with EXACTLY one line, each
        // starting with its number ... Output {n} lines and nothing else". An
        // unescaped newline put an unnumbered line in the middle of the list,
        // and a ratifier folding answer line k onto item k then wrote a
        // verdict onto the wrong entry.
        let mut object = WorkingObject::open(regime());
        object
            .apply_turn(&[
                add("e1", "first note", 1, 0),
                add("e2", "second note\nwith a continuation", 1, 1),
                add("e3", "third note", 1, 2),
            ])
            .expect("three adds apply");
        let mut controller = Controller::open(
            policy("seam_every_turns = 1\n"),
            &object,
            Scripted::silent(),
        );
        controller.begin_turn();
        controller.settle(&mut object).expect("nothing folds");

        let ask = &controller.ratifier().seen[0];
        assert_eq!(ask.items.len(), 3);
        assert!(ask.text.contains("Output 3 lines and nothing else"));
        let numbered = ask.text.split("\n\n").last().expect("the items block");
        assert_eq!(
            numbered.lines().count(),
            3,
            "three items, three lines: {numbered}"
        );
        for (index, line) in numbered.lines().enumerate() {
            assert!(
                line.starts_with(&format!("{}. ", index + 1)),
                "line {} does not begin with its number: {line}",
                index + 1
            );
        }
    }

    #[test]
    fn a_cadence_too_large_for_the_field_is_refused_rather_than_clamped() {
        assert_eq!(
            Policy::from_regimen(
                &regimen::parse("seam_every_turns = 5000000000\n").expect("a regimen")
            ),
            Err(PolicyError::DoesNotFit {
                key: "seam_every_turns",
                value: 5_000_000_000,
            }),
            "it used to clamp to u32::MAX -- a declared cadence becoming a \
             different, effectively-never one with no error anywhere"
        );
    }

    #[test]
    fn a_regimen_with_no_phases_refuses_a_proposal_as_having_no_graph() {
        // Its own refusal rather than `not_a_phase`: a session with no phase
        // graph is the scale-adaptive case working as declared, not a graph
        // that happens to be missing an edge.
        let mut object = three_facts();
        let mut controller = Controller::open(
            policy("seam_every_turns = 3\n"),
            &object,
            Scripted::silent(),
        );
        controller.begin_turn();
        assert_eq!(
            controller.propose("implement"),
            Decision::Refused(Refusal::NoGraph)
        );
        assert!(
            controller
                .settle(&mut object)
                .expect("nothing folds")
                .is_none()
        );
    }

    #[test]
    fn a_controller_that_settles_before_its_first_turn_fires_nothing() {
        // Every number divides zero, so without the `turn > 0` guard a cadence
        // fires a seam over an empty session before it has begun. Only the
        // manifest's drift guard caught this, which is a red for the wrong
        // reason.
        let mut object = three_facts();
        let mut controller = Controller::open(
            policy("seam_every_turns = 1\n"),
            &object,
            Scripted::silent(),
        );
        assert!(
            controller
                .settle(&mut object)
                .expect("nothing folds")
                .is_none(),
            "turn zero is before the session started"
        );
        assert!(controller.seams().is_empty());
    }

    #[test]
    fn one_turn_gets_one_seam() {
        let mut object = three_facts();
        let mut controller = Controller::open(
            policy("seam_every_turns = 1\n"),
            &object,
            Scripted::silent(),
        );
        controller.begin_turn();
        assert!(controller.settle(&mut object).expect("folds").is_some());
        assert!(
            controller.settle(&mut object).expect("folds").is_none(),
            "a second settle in one turn used to fire a second seam at the same \
             turn index -- two full re-prefills for one prompt"
        );
        assert_eq!(controller.seams().len(), 1);
    }

    #[test]
    fn the_cadence_is_absolute_so_a_seam_can_land_beside_another() {
        // Documented rather than fixed: the cadence counts turns, not
        // turns-since-the-last-seam, so an operator boundary on turn 4 under
        // `seam_every_turns = 5` is followed by a cadence seam on turn 5. A
        // reader would reasonably predict the cadence restarts, and it does
        // not.
        let mut object = three_facts();
        let mut controller = Controller::open(
            policy("seam_every_turns = 5\n"),
            &object,
            Scripted::silent(),
        );
        for turn in 1..=5_u32 {
            controller.begin_turn();
            if turn == 4 {
                controller.operator_declares_a_boundary();
            }
            controller.settle(&mut object).expect("the fold applies");
        }
        assert_eq!(
            controller
                .seams()
                .iter()
                .map(|seam| (seam.at_turn, seam.reason))
                .collect::<Vec<_>>(),
            vec![(4, Reason::Operator), (5, Reason::Cadence)]
        );
    }

    #[test]
    fn a_seam_records_the_object_version_its_dumps_are_of() {
        // #27 asks for a versioned dump either side. The dumps carry no header
        // -- it would appear in every diff -- so the version is on the seam.
        let mut object = three_facts();
        let before = object.version();
        let mut controller = Controller::open(
            policy("seam_every_turns = 1\n"),
            &object,
            Scripted::answering(vec![vec![add("e4", "a fact the audit added", 1, 0)]]),
        );
        controller.begin_turn();
        let seam = controller
            .settle(&mut object)
            .expect("the fold applies")
            .expect("a seam");
        assert_eq!(seam.object_version, object.version());
        assert_ne!(
            seam.object_version, before,
            "the fold moved the object, and the seam says which version its `after` is"
        );
    }

    #[test]
    fn the_seams_vocabularies_are_the_words_a_record_carries() {
        assert_eq!(
            Reason::ALL.iter().map(|r| r.tag()).collect::<Vec<_>>(),
            ["operator", "phase", "budget", "cadence"],
            "declaration order is precedence: an explicit act outranks every derived one"
        );
        assert_eq!(
            Blocked::ALL.iter().map(|b| b.tag()).collect::<Vec<_>>(),
            ["no_pinned_ask", "nothing_to_audit"]
        );
        assert_eq!(
            Refusal::ALL.iter().map(|r| r.tag()).collect::<Vec<_>>(),
            ["no_graph", "not_a_phase", "no_edge", "already_there"]
        );
    }

    // -----------------------------------------------------------------------
    // the policy, read from a regimen
    // -----------------------------------------------------------------------

    #[test]
    fn a_policy_is_read_from_the_regimen_or_refused_with_a_reason() {
        let read = |text: &str| Policy::from_regimen(&regimen::parse(text).expect("a regimen"));

        let full = read(
            "seam_every_turns = 3\n\
             seam_at_working_set_bytes = 4096\n\
             phases = [\"plan\", \"implement\"]\n\
             [phase_transitions]\n\
             plan = [\"implement\"]\n",
        )
        .expect("a policy");
        assert_eq!(full.every_turns, Some(3));
        assert_eq!(full.at_working_set_bytes, Some(4096));
        assert_eq!(
            full.phases.phases(),
            ["plan".to_owned(), "implement".to_owned()]
        );
        assert_eq!(
            full.phases.decide(Some("plan"), "implement"),
            Decision::Ratified
        );

        assert_eq!(
            read("seam_every_turns = 0\n"),
            Err(PolicyError::NotPositive("seam_every_turns")),
            "zero would fire on every turn or on none depending on how it is read; \
             the way to declare no cadence is to leave the key out"
        );
        assert_eq!(
            read("seam_every_turns = \"three\"\n"),
            Err(PolicyError::NotAnInteger("seam_every_turns"))
        );
        assert_eq!(
            read("phases = \"plan\"\n"),
            Err(PolicyError::NotAListOfNames("phases".to_owned()))
        );
        assert_eq!(
            read("phases = [\"plan\", \"plan\"]\n"),
            Err(PolicyError::DuplicatePhase("plan".to_owned())),
            "two phases with one name make an edge's target ambiguous"
        );
        assert_eq!(
            read("phases = [\"plan\"]\n[phase_transitions]\nplan = [\"ship\"]\n"),
            Err(PolicyError::UnknownPhase {
                named: "ship".to_owned(),
                under: "plan".to_owned(),
            }),
            "an edge to a phase that does not exist is a rule nothing can take"
        );
        assert_eq!(
            read("[phase_transitions]\nplan = [\"implement\"]\n"),
            Err(PolicyError::TransitionsWithoutPhases)
        );
    }

    // -----------------------------------------------------------------------
    // the render
    // -----------------------------------------------------------------------

    #[test]
    fn the_render_is_a_pure_function_of_the_object_and_the_phase() {
        let object = three_facts();
        assert_eq!(
            render::render(&object, Some("plan")),
            render::render(&object, Some("plan")),
            "two renders of the same object in the same phase are the same bytes, \
             which is the only reason the byte-identity claim can be checked"
        );
        assert_ne!(
            render::render(&object, Some("plan")),
            render::render(&object, Some("implement"))
        );
        assert_ne!(
            render::render(&object, None),
            render::render(&object, Some("plan")),
            "no phase renders as `-` rather than as an absent line: a field that \
             disappears makes two prompts differ in shape as well as content"
        );

        let rendered = render::render(&object, None);
        assert!(rendered.contains("arm: an-arm"));
        assert!(rendered.contains("substrate: a-substrate"));
        assert!(rendered.contains("dogma_version: 1"));
        assert!(rendered.contains("phase: -"));
    }

    #[test]
    fn the_working_set_is_measured_from_what_would_be_sent() {
        let empty = WorkingObject::open(regime());
        assert_eq!(render::working_set_bytes(&empty), 0);

        let object = three_facts();
        let measured = render::working_set_bytes(&object);
        assert!(measured > 0);
        // Not equal to the render's length: the render carries a regime header
        // the working set is not responsible for. The claim is that the
        // measurement is of the entries, and it is bounded by the whole.
        assert!(
            measured < render::render(&object, None).len() as u64,
            "the working set is the entries, not the whole prompt"
        );
    }

    #[test]
    fn the_working_set_measures_size_and_not_a_count_of_entries() {
        // `measured > 0` and `measured < the whole render` are both true of a
        // count of entries, so neither says what is being measured. What
        // separates them: one long entry is a bigger prompt than three short
        // ones, and a count says the opposite.
        let mut three_short = WorkingObject::open(regime());
        three_short
            .apply_turn(&[
                add("a", "x", 1, 0),
                add("b", "y", 1, 1),
                add("c", "z", 1, 2),
            ])
            .expect("three adds apply");
        let mut one_long = WorkingObject::open(regime());
        one_long
            .apply_turn(&[add("a", &"x".repeat(500), 1, 0)])
            .expect("one add applies");

        assert!(
            render::working_set_bytes(&one_long) > render::working_set_bytes(&three_short),
            "one 500-byte entry against three of one byte: {} against {}",
            render::working_set_bytes(&one_long),
            render::working_set_bytes(&three_short)
        );
    }

    /// A seam is a value a caller can hold onto after the controller moves on.
    #[test]
    fn a_seam_returned_is_the_seam_recorded() {
        let mut object = three_facts();
        let mut controller = Controller::open(
            policy("seam_every_turns = 1\n"),
            &object,
            Scripted::silent(),
        );
        controller.begin_turn();
        let returned: Seam = controller
            .settle(&mut object)
            .expect("nothing folds")
            .expect("a seam");
        assert_eq!(controller.seams(), [returned]);
    }
}
