//! The conformance harness for every format in [`diet::formats`].
//!
//! This is the only place format conformance is asserted. It walks
//! `diet/formats/<name>/fixtures/`, requires that `valid/` and `invalid/`
//! account for every file in them, and checks each case against its pair:
//! a `valid/<case>.<ext>` must parse to exactly its `valid/<case>.expected.json`,
//! and an `invalid/<case>.<ext>` must be rejected.
//!
//! Two properties of the harness itself are load-bearing:
//!
//! * **The case extension is data, carried by [`Format`].** It was hard-coded
//!   to `toml` while there was one format. That alone would have been caught
//!   -- the empty-bucket assertion goes red on a bucket with no cases -- but
//!   only as "this format has no fixtures at all"; what the field buys is that
//!   the pairing and parse assertions walk the right files rather than none.
//! * **Every format gets a named test module**, generated by `per_format!`
//!   from the same token list that declares [`NAMED`]. That makes
//!   `cargo test -- formats::decline` a real command rather than a filter
//!   that matches nothing and exits 0, and the two cannot drift because one
//!   macro invocation produces both.
//!
//! There is no way to redirect the fixture root. `verify.sh --selftest` injects
//! a non-conforming fixture into a sandbox COPY of the repository and runs the
//! real `verify.sh` there, so what goes red is the gate itself rather than a
//! test-only path -- and no ambient environment variable can point this
//! harness at a corpus that is not the committed one.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use diet::formats::interview::{Completion, Outcome};
use diet::formats::regimen::Value;
use diet::formats::{FORMATS, Format, decline, interview, record, regimen};
use serde_json::{Map, Value as Json};

/// Where fixtures live: the committed tree, and nowhere else.
///
/// This was once redirectable by an environment variable, so that a candidate
/// fixture tree could be checked without touching the committed one. Nothing
/// used it, and it meant four files in a temporary directory could stand in
/// for the entire corpus with the whole gate still green -- an escape hatch
/// from the only thing this file does.
fn formats_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("formats")
}

/// The [`Format`] a named test module covers.
///
/// A module whose name is absent from [`FORMATS`] is a module asserting
/// nothing about anything, so it panics rather than skipping.
fn format_named(name: &str) -> &'static Format {
    diet::formats::format(name)
        .unwrap_or_else(|| panic!("`{name}` has a test module but is absent from FORMATS"))
}

/// Parse `source` as `format` and render the result as tagged JSON, so that a
/// fixture pins the parsed *type* and not merely the parsed text.
///
/// Takes bytes, not text: a format has to return a verdict on whatever is on
/// disk. Decoding in here means a non-UTF-8 case is a rejection with a reason,
/// where reading it as a `String` first would abort the whole harness on a
/// fixture whose entire point is being unreadable.
///
/// Adding a name to [`FORMATS`] without wiring it here is a panic, not a
/// silently skipped format.
fn parse_to_json(format: &str, source: &[u8]) -> Result<Json, String> {
    let source = std::str::from_utf8(source).map_err(|err| format!("not UTF-8: {err}"))?;
    match format {
        "regimen" => regimen::parse(source)
            .map(|parsed| {
                let mut map = Map::new();
                for (key, value) in parsed.iter() {
                    let tagged = match value {
                        Value::String(text) => serde_json::json!({ "string": text }),
                        Value::Integer(number) => serde_json::json!({ "integer": number }),
                        Value::Boolean(flag) => serde_json::json!({ "boolean": flag }),
                    };
                    map.insert(key.to_owned(), tagged);
                }
                Json::Object(map)
            })
            .map_err(|err| err.to_string()),
        // Through `classify`, not `parse`. `classify` is what every caller is
        // told to use, and a corpus that exercised only `parse` left it able
        // to return `Content` for everything with the whole gate green.
        "decline" => match decline::classify(source) {
            decline::Classification::Decline(parsed) => Ok(serde_json::json!({
                "decline": {
                    "subject": parsed.subject,
                    "marker": parsed.marker,
                    "scope": parsed.scope,
                    "reason": parsed.reason,
                }
            })),
            decline::Classification::Content => Err(match decline::parse(source) {
                Err(err) => err.to_string(),
                Ok(_) => "classify says content where parse succeeds: \
                          the two disagree about the same bytes"
                    .to_owned(),
            }),
        },
        "interview" => interview::parse(source)
            .map(|answer| {
                let fields: Vec<Json> = answer
                    .fields
                    .iter()
                    .map(|field| {
                        let tag = field.tag.as_ref().map_or(Json::Null, |tag| {
                            serde_json::json!({
                                "kind": tag.kind.canonical_tag(),
                                "as_written": tag.as_written,
                            })
                        });
                        let outcome = match &field.outcome {
                            Outcome::Value(text) => serde_json::json!({ "value": text }),
                            Outcome::Decline(declined) => serde_json::json!({
                                "decline": {
                                    "marker": declined.marker,
                                    "scope": declined.scope,
                                    "reason": declined.reason,
                                }
                            }),
                            Outcome::Unparseable => Json::from("unparseable"),
                        };
                        serde_json::json!({
                            "tag": tag,
                            "raw": field.raw,
                            "outcome": outcome,
                        })
                    })
                    .collect();
                let completion = match answer.completion {
                    Completion::Complete => Json::from("complete"),
                    Completion::Empty => Json::from("empty"),
                    Completion::Truncated(signal) => {
                        serde_json::json!({ "truncated": signal.name() })
                    }
                };
                let wrapper = answer.wrapper.as_ref().map_or(Json::Null, |wrapper| {
                    serde_json::json!({
                        "open": wrapper.open,
                        "close": wrapper.close,
                        "fields_inside": wrapper.fields_inside,
                    })
                });
                serde_json::json!({
                    "completion": completion,
                    "wrapper": wrapper,
                    "fields": fields,
                })
            })
            .map_err(|err| err.to_string()),
        "record" => record::parse(source)
            .map(|parsed| {
                // Three things, each pinning something different: the regime
                // trio a report's front-matter mirrors, which event kinds the
                // case exercises, and the canonical rendering -- which pins
                // every value's type and spelling byte for byte, and is short
                // enough that a reviewer can check it against the input line
                // by line.
                serde_json::json!({
                    "regime": {
                        "arm": parsed.regime().arm,
                        "substrate": parsed.regime().substrate.name,
                        "dogma_version": parsed.regime().dogma_version,
                    },
                    "kinds": parsed.kinds().iter().map(|kind| kind.tag()).collect::<Vec<_>>(),
                    "canonical": record::render(&parsed),
                })
            })
            .map_err(|err| err.to_string()),
        other => panic!("format `{other}` is listed in FORMATS but not wired into the harness"),
    }
}

/// Every file in `dir`, sorted, so failures are reported in a stable order.
fn files_in(dir: &Path) -> Vec<PathBuf> {
    let mut paths: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|err| panic!("cannot read fixture directory {}: {err}", dir.display()))
        .map(|entry| {
            entry
                .expect("a readable directory yields readable entries")
                .path()
        })
        .collect();
    paths.sort();
    paths
}

/// Every entry directly in `dir`, or nothing if `dir` cannot be read. Used
/// where a missing directory is already reported by another check.
fn files_in_or_empty(dir: &Path) -> Vec<PathBuf> {
    if dir.is_dir() {
        files_in(dir)
    } else {
        Vec::new()
    }
}

/// The case files in `dir` -- those carrying `format`'s case extension.
fn cases_in(format: &Format, dir: &Path) -> Vec<PathBuf> {
    files_in_or_empty(dir)
        .into_iter()
        .filter(|path| {
            path.extension()
                .is_some_and(|ext| ext == format.case_extension)
        })
        .collect()
}

/// A fixture case, as bytes. A case may deliberately not be text.
fn read_case(path: &Path) -> Vec<u8> {
    std::fs::read(path).unwrap_or_else(|err| panic!("cannot read {}: {err}", path.display()))
}

/// A companion file (`.expected.json`, `.reason`), as text. These are ours,
/// not fixtures, so they must be readable.
fn read_companion(path: &Path) -> String {
    std::fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("cannot read {}: {err}", path.display()))
}

fn report(failures: &[String]) {
    assert!(
        failures.is_empty(),
        "{} conformance failure(s):\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

// --------------------------------------------------------------------------
// the four assertions, each scoped to one format
// --------------------------------------------------------------------------

fn assert_grammar_and_populated_buckets(format: &Format) {
    let root = formats_dir();
    let mut failures = Vec::new();

    let grammar = root.join(format.name).join("grammar.pest");
    if !grammar.is_file() {
        failures.push(format!(
            "{}: missing grammar at {}",
            format.name,
            grammar.display()
        ));
    }
    for bucket in ["valid", "invalid"] {
        let dir = root.join(format.name).join("fixtures").join(bucket);
        if !dir.is_dir() {
            failures.push(format!(
                "{}: missing fixture bucket {}",
                format.name,
                dir.display()
            ));
            continue;
        }
        // A bucket with no cases makes every other assertion in this file
        // iterate nothing and pass, which is the failure this repository
        // exists to make impossible.
        if cases_in(format, &dir).is_empty() {
            failures.push(format!(
                "{}: fixture bucket {bucket} holds no *.{} case",
                format.name, format.case_extension
            ));
        }
    }

    report(&failures);
}

fn assert_fixtures_are_paired(format: &Format) {
    let fixtures = formats_dir().join(format.name).join("fixtures");
    let mut failures = Vec::new();

    for case in cases_in(format, &fixtures.join("valid")) {
        if !case.with_extension("expected.json").is_file() {
            failures.push(format!(
                "{}: {} has no expected.json",
                format.name,
                case.display()
            ));
        }
    }
    for case in cases_in(format, &fixtures.join("invalid")) {
        if !case.with_extension("reason").is_file() {
            failures.push(format!(
                "{}: {} has no .reason",
                format.name,
                case.display()
            ));
        }
    }

    // The other direction: nothing in a bucket may be an orphan or a stray. A
    // fixture directory that quietly accumulates unread files is a fixture
    // directory that quietly stops covering things.
    for (bucket, companion) in [("valid", "expected.json"), ("invalid", "reason")] {
        for path in files_in_or_empty(&fixtures.join(bucket)) {
            if path
                .extension()
                .is_some_and(|ext| ext == format.case_extension)
            {
                continue;
            }
            let name = path
                .file_name()
                .and_then(std::ffi::OsStr::to_str)
                .unwrap_or_default();
            let Some(stem) = name.strip_suffix(&format!(".{companion}")) else {
                failures.push(format!("{}: stray file {}", format.name, path.display()));
                continue;
            };
            let case = fixtures
                .join(bucket)
                .join(format!("{stem}.{}", format.case_extension));
            if !case.is_file() {
                failures.push(format!(
                    "{}: orphaned companion {}",
                    format.name,
                    path.display()
                ));
            }
        }
    }

    report(&failures);
}

fn assert_valid_fixtures_parse_to_their_expected_value(format: &Format) {
    let dir = formats_dir()
        .join(format.name)
        .join("fixtures")
        .join("valid");
    let mut failures = Vec::new();

    for case in cases_in(format, &dir) {
        let expected_path = case.with_extension("expected.json");
        if !expected_path.is_file() {
            continue; // reported by the pairing assertion
        }
        let expected: Json = match serde_json::from_str(&read_companion(&expected_path)) {
            Ok(json) => json,
            Err(err) => {
                failures.push(format!("{}: unreadable expectation: {err}", case.display()));
                continue;
            }
        };
        match parse_to_json(format.name, &read_case(&case)) {
            Ok(actual) if actual == expected => {}
            Ok(actual) => failures.push(format!(
                "{}: parsed to {actual}, expected {expected}",
                case.display()
            )),
            Err(err) => failures.push(format!("{}: rejected: {err}", case.display())),
        }
    }

    report(&failures);
}

fn assert_invalid_fixtures_are_rejected(format: &Format) {
    let dir = formats_dir()
        .join(format.name)
        .join("fixtures")
        .join("invalid");
    let mut failures = Vec::new();
    // The rejection each case produced, so that two cases pinning one rule
    // can be told apart from two cases pinning two.
    let mut rejections: BTreeMap<String, PathBuf> = BTreeMap::new();

    for case in cases_in(format, &dir) {
        let reason = case.with_extension("reason");
        let reason = if reason.is_file() {
            read_companion(&reason).trim().to_owned()
        } else {
            "no reason recorded".to_owned()
        };
        match parse_to_json(format.name, &read_case(&case)) {
            Ok(parsed) => failures.push(format!(
                "{}: accepted as {parsed}, but must be rejected: {reason}",
                case.display()
            )),
            // Two fixtures rejected by the identical message are one fixture
            // and a duplicate: whichever is second pins nothing the first does
            // not, and its `.reason` describes a rule it never reaches. One
            // such pair shipped -- a case whose reason named a rule that is
            // unreachable for any document holding a row.
            Err(rejection) => {
                if let Some(first) = rejections.insert(rejection.clone(), case.clone()) {
                    failures.push(format!(
                        "{} and {} are both rejected by `{rejection}`, so the \
                         second pins nothing the first does not",
                        first.display(),
                        case.display()
                    ));
                }
            }
        }
    }

    report(&failures);
}

// --------------------------------------------------------------------------
// per-format entry points
// --------------------------------------------------------------------------

/// Generate a test module per format, and the [`NAMED`] list from the same
/// tokens.
///
/// The two cannot drift: a name here produces both a module and an entry in
/// the list `every_format_has_a_named_test_module` checks against [`FORMATS`].
macro_rules! per_format {
    ($($name:ident),+ $(,)?) => {
        $(
            mod $name {
                use super::super::*;

                fn covered() -> &'static Format { format_named(stringify!($name)) }

                #[test]
                fn has_a_grammar_and_populated_fixture_buckets() {
                    assert_grammar_and_populated_buckets(covered());
                }

                #[test]
                fn every_fixture_file_is_paired() {
                    assert_fixtures_are_paired(covered());
                }

                #[test]
                fn valid_fixtures_parse_to_their_expected_value() {
                    assert_valid_fixtures_parse_to_their_expected_value(covered());
                }

                #[test]
                fn invalid_fixtures_are_rejected() {
                    assert_invalid_fixtures_are_rejected(covered());
                }
            }
        )+

        /// The formats with a named test module. Generated beside the modules
        /// themselves so the coverage check below cannot be satisfied by a
        /// list entry alone.
        const NAMED: &[&str] = &[$(stringify!($name)),+];
    };
}

mod formats {
    // The generated modules reach the harness through `super::super::*`; only
    // the coverage check below needs anything named here.
    use super::FORMATS;
    use std::collections::BTreeSet;

    per_format!(decline, interview, record, regimen);

    /// A format in [`FORMATS`] with no module here is a format nobody can run
    /// on its own, and -- worse -- `cargo test -- formats::<name>` for it
    /// matches no test and exits 0. An acceptance command that cannot fail is
    /// not an acceptance command.
    #[test]
    fn every_format_has_a_named_test_module() {
        let declared: BTreeSet<&str> = FORMATS.iter().map(|format| format.name).collect();
        let named: BTreeSet<&str> = NAMED.iter().copied().collect();
        assert_eq!(
            declared, named,
            "FORMATS and the per_format! list disagree: \
             every format needs a named test module, and every module a format"
        );
    }
}

// --------------------------------------------------------------------------
// cross-format invariants
// --------------------------------------------------------------------------

/// Without this, emptying `FORMATS` would make every sweep iterate nothing
/// and pass. A harness that covers no formats must be red, not quiet.
#[test]
fn the_harness_covers_at_least_one_format() {
    assert!(
        !FORMATS.is_empty(),
        "FORMATS is empty, so this harness covers nothing"
    );
}

/// A format directory on disk that `FORMATS` does not name is a format with
/// no grammar requirement and no fixture requirement at all. Coverage must
/// not be a hand-maintained opinion about what exists.
#[test]
fn no_format_directory_is_undeclared() {
    let root = formats_dir();
    let declared: BTreeSet<&str> = FORMATS.iter().map(|format| format.name).collect();
    let mut failures = Vec::new();

    for entry in files_in_or_empty(&root) {
        if !entry.is_dir() {
            continue;
        }
        let Some(name) = entry.file_name().and_then(std::ffi::OsStr::to_str) else {
            failures.push(format!("{}: unreadable directory name", entry.display()));
            continue;
        };
        if !declared.contains(name) {
            failures.push(format!(
                "{name}: has a directory under formats/ but is absent from FORMATS, \
                 so nothing requires it to have a grammar or fixtures"
            ));
        }
    }

    report(&failures);
}
