//! The conformance harness for every format in [`diet::formats`].
//!
//! This is the only place format conformance is asserted. It walks
//! `diet/formats/<name>/fixtures/`, requires that `valid/` and `invalid/`
//! account for every file in them, and checks each case against its pair:
//! a `valid/<case>.<ext>` must parse to exactly its `valid/<case>.expected.json`,
//! and an `invalid/<case>.<ext>` must be rejected.
//!
//! Two properties of the harness itself are load-bearing:
//!
//! * **The case extension is data, carried by [`Format`].** It was hard-coded
//!   to `toml` while there was one format. That alone would have been caught
//!   -- the empty-bucket assertion goes red on a bucket with no cases -- but
//!   only as "this format has no fixtures at all"; what the field buys is that
//!   the pairing and parse assertions walk the right files rather than none.
//! * **Every format gets a named test module**, generated by `per_format!`
//!   from the same token list that declares [`NAMED`]. That makes
//!   `cargo test -- formats::decline` a real command rather than a filter
//!   that matches nothing and exits 0, and the two cannot drift because one
//!   macro invocation produces both.
//!
//! There is no way to redirect the fixture root. `verify.sh --selftest` injects
//! a non-conforming fixture into a sandbox COPY of the repository and runs the
//! real `verify.sh` there, so what goes red is the gate itself rather than a
//! test-only path -- and no ambient environment variable can point this
//! harness at a corpus that is not the committed one.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use diet::formats::record::json::Value;
use diet::formats::{FORMATS, Format};
use serde_json::Value as Json;

/// Where fixtures live: the committed tree, and nowhere else.
///
/// This was once redirectable by an environment variable, so that a candidate
/// fixture tree could be checked without touching the committed one. Nothing
/// used it, and it meant four files in a temporary directory could stand in
/// for the entire corpus with the whole gate still green -- an escape hatch
/// from the only thing this file does.
fn formats_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("formats")
}

/// The [`Format`] a named test module covers.
///
/// A module whose name is absent from [`FORMATS`] is a module asserting
/// nothing about anything, so it panics rather than skipping.
fn format_named(name: &str) -> &'static Format {
    diet::formats::format(name)
        .unwrap_or_else(|| panic!("`{name}` has a test module but is absent from FORMATS"))
}

/// Parse `source` with `format` and render the result as JSON, so that a
/// fixture pins the parsed *type* and not merely the parsed text.
///
/// Takes bytes, not text: a format has to return a verdict on whatever is on
/// disk. Decoding in here means a non-UTF-8 case is a rejection with a reason,
/// where reading it as a `String` first would abort the whole harness on a
/// fixture whose entire point is being unreadable.
///
/// Dispatch is the format's own `project` function pointer. It used to be a
/// match on the format's NAME that panicked on one it did not know -- a guard
/// that fires at run time, where this one fires at compile time, and the same
/// projection the `diet` CLI emits rather than a second one that agrees today.
fn parse_to_json(format: &Format, source: &[u8]) -> Result<Json, String> {
    let source = std::str::from_utf8(source).map_err(|err| format!("not UTF-8: {err}"))?;
    (format.project)(source).map(|value| as_json(&value))
}

/// The record's value space as `serde_json`, for comparison against a fixture.
fn as_json(value: &Value) -> Json {
    match value {
        Value::Object(members) => Json::Object(
            members
                .iter()
                .map(|(key, member)| (key.clone(), as_json(member)))
                .collect(),
        ),
        Value::Array(items) => Json::Array(items.iter().map(as_json).collect()),
        Value::String(text) => Json::String(text.clone()),
        Value::Integer(number) => Json::from(*number),
        // Exact in the record and exact here: parsed from its own digits, not
        // from a float that happened to round there.
        Value::Decimal(number) => number
            .as_str()
            .parse::<serde_json::Number>()
            .map_or_else(|_| Json::String(number.as_str().to_owned()), Json::Number),
        Value::Boolean(flag) => Json::Bool(*flag),
    }
}

/// Every file in `dir`, sorted, so failures are reported in a stable order.
fn files_in(dir: &Path) -> Vec<PathBuf> {
    let mut paths: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|err| panic!("cannot read fixture directory {}: {err}", dir.display()))
        .map(|entry| {
            entry
                .expect("a readable directory yields readable entries")
                .path()
        })
        .collect();
    paths.sort();
    paths
}

/// Every entry directly in `dir`, or nothing if `dir` cannot be read. Used
/// where a missing directory is already reported by another check.
fn files_in_or_empty(dir: &Path) -> Vec<PathBuf> {
    if dir.is_dir() {
        files_in(dir)
    } else {
        Vec::new()
    }
}

/// The case files in `dir` -- those carrying `format`'s case extension.
fn cases_in(format: &Format, dir: &Path) -> Vec<PathBuf> {
    files_in_or_empty(dir)
        .into_iter()
        .filter(|path| {
            path.extension()
                .is_some_and(|ext| ext == format.case_extension)
        })
        .collect()
}

/// A fixture case, as bytes. A case may deliberately not be text.
fn read_case(path: &Path) -> Vec<u8> {
    std::fs::read(path).unwrap_or_else(|err| panic!("cannot read {}: {err}", path.display()))
}

/// A companion file (`.expected.json`, `.reason`), as text. These are ours,
/// not fixtures, so they must be readable.
fn read_companion(path: &Path) -> String {
    std::fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("cannot read {}: {err}", path.display()))
}

fn report(failures: &[String]) {
    assert!(
        failures.is_empty(),
        "{} conformance failure(s):\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

// --------------------------------------------------------------------------
// the four assertions, each scoped to one format
// --------------------------------------------------------------------------

fn assert_grammar_and_populated_buckets(format: &Format) {
    let root = formats_dir();
    let mut failures = Vec::new();

    let grammar = root.join(format.name).join("grammar.pest");
    if !grammar.is_file() {
        failures.push(format!(
            "{}: missing grammar at {}",
            format.name,
            grammar.display()
        ));
    }
    for bucket in ["valid", "invalid"] {
        let dir = root.join(format.name).join("fixtures").join(bucket);
        if !dir.is_dir() {
            failures.push(format!(
                "{}: missing fixture bucket {}",
                format.name,
                dir.display()
            ));
            continue;
        }
        // A bucket with no cases makes every other assertion in this file
        // iterate nothing and pass, which is the failure this repository
        // exists to make impossible.
        if cases_in(format, &dir).is_empty() {
            failures.push(format!(
                "{}: fixture bucket {bucket} holds no *.{} case",
                format.name, format.case_extension
            ));
        }
    }

    report(&failures);
}

fn assert_fixtures_are_paired(format: &Format) {
    let fixtures = formats_dir().join(format.name).join("fixtures");
    let mut failures = Vec::new();

    for case in cases_in(format, &fixtures.join("valid")) {
        if !case.with_extension("expected.json").is_file() {
            failures.push(format!(
                "{}: {} has no expected.json",
                format.name,
                case.display()
            ));
        }
    }
    for case in cases_in(format, &fixtures.join("invalid")) {
        if !case.with_extension("reason").is_file() {
            failures.push(format!(
                "{}: {} has no .reason",
                format.name,
                case.display()
            ));
        }
    }

    // The other direction: nothing in a bucket may be an orphan or a stray. A
    // fixture directory that quietly accumulates unread files is a fixture
    // directory that quietly stops covering things.
    for (bucket, companion) in [("valid", "expected.json"), ("invalid", "reason")] {
        for path in files_in_or_empty(&fixtures.join(bucket)) {
            if path
                .extension()
                .is_some_and(|ext| ext == format.case_extension)
            {
                continue;
            }
            let name = path
                .file_name()
                .and_then(std::ffi::OsStr::to_str)
                .unwrap_or_default();
            let Some(stem) = name.strip_suffix(&format!(".{companion}")) else {
                failures.push(format!("{}: stray file {}", format.name, path.display()));
                continue;
            };
            let case = fixtures
                .join(bucket)
                .join(format!("{stem}.{}", format.case_extension));
            if !case.is_file() {
                failures.push(format!(
                    "{}: orphaned companion {}",
                    format.name,
                    path.display()
                ));
            }
        }
    }

    report(&failures);
}

fn assert_valid_fixtures_parse_to_their_expected_value(format: &Format) {
    let dir = formats_dir()
        .join(format.name)
        .join("fixtures")
        .join("valid");
    let mut failures = Vec::new();

    for case in cases_in(format, &dir) {
        let expected_path = case.with_extension("expected.json");
        if !expected_path.is_file() {
            continue; // reported by the pairing assertion
        }
        let expected: Json = match serde_json::from_str(&read_companion(&expected_path)) {
            Ok(json) => json,
            Err(err) => {
                failures.push(format!("{}: unreadable expectation: {err}", case.display()));
                continue;
            }
        };
        match parse_to_json(format, &read_case(&case)) {
            Ok(actual) if actual == expected => {}
            Ok(actual) => failures.push(format!(
                "{}: parsed to {actual}, expected {expected}",
                case.display()
            )),
            Err(err) => failures.push(format!("{}: rejected: {err}", case.display())),
        }
    }

    report(&failures);
}

fn assert_invalid_fixtures_are_rejected(format: &Format) {
    let dir = formats_dir()
        .join(format.name)
        .join("fixtures")
        .join("invalid");
    let mut failures = Vec::new();
    // The rejection each case produced, so that two cases pinning one rule
    // can be told apart from two cases pinning two.
    let mut rejections: BTreeMap<String, PathBuf> = BTreeMap::new();

    for case in cases_in(format, &dir) {
        let reason = case.with_extension("reason");
        let reason = if reason.is_file() {
            read_companion(&reason).trim().to_owned()
        } else {
            "no reason recorded".to_owned()
        };
        match parse_to_json(format, &read_case(&case)) {
            Ok(parsed) => failures.push(format!(
                "{}: accepted as {parsed}, but must be rejected: {reason}",
                case.display()
            )),
            // Two fixtures rejected by the identical message are one fixture
            // and a duplicate: whichever is second pins nothing the first does
            // not, and its `.reason` describes a rule it never reaches. One
            // such pair shipped -- a case whose reason named a rule that is
            // unreachable for any document holding a row.
            Err(rejection) => {
                if let Some(first) = rejections.insert(rejection.clone(), case.clone()) {
                    failures.push(format!(
                        "{} and {} are both rejected by `{rejection}`, so the \
                         second pins nothing the first does not",
                        first.display(),
                        case.display()
                    ));
                }
            }
        }
    }

    report(&failures);
}

// --------------------------------------------------------------------------
// per-format entry points
// --------------------------------------------------------------------------

/// Generate a test module per format, and the [`NAMED`] list from the same
/// tokens.
///
/// The two cannot drift: a name here produces both a module and an entry in
/// the list `every_format_has_a_named_test_module` checks against [`FORMATS`].
macro_rules! per_format {
    ($($name:ident),+ $(,)?) => {
        $(
            mod $name {
                use super::super::*;

                fn covered() -> &'static Format { format_named(stringify!($name)) }

                #[test]
                fn has_a_grammar_and_populated_fixture_buckets() {
                    assert_grammar_and_populated_buckets(covered());
                }

                #[test]
                fn every_fixture_file_is_paired() {
                    assert_fixtures_are_paired(covered());
                }

                #[test]
                fn valid_fixtures_parse_to_their_expected_value() {
                    assert_valid_fixtures_parse_to_their_expected_value(covered());
                }

                #[test]
                fn invalid_fixtures_are_rejected() {
                    assert_invalid_fixtures_are_rejected(covered());
                }
            }
        )+

        /// The formats with a named test module. Generated beside the modules
        /// themselves so the coverage check below cannot be satisfied by a
        /// list entry alone.
        const NAMED: &[&str] = &[$(stringify!($name)),+];
    };
}

mod formats {
    // The generated modules reach the harness through `super::super::*`; only
    // the coverage check below needs anything named here.
    use super::FORMATS;
    use std::collections::BTreeSet;

    per_format!(
        decline,
        interview,
        operating_points,
        record,
        regimen,
        shell,
        verdict
    );

    /// A format in [`FORMATS`] with no module here is a format nobody can run
    /// on its own, and -- worse -- `cargo test -- formats::<name>` for it
    /// matches no test and exits 0. An acceptance command that cannot fail is
    /// not an acceptance command.
    #[test]
    fn every_format_has_a_named_test_module() {
        let declared: BTreeSet<&str> = FORMATS.iter().map(|format| format.name).collect();
        let named: BTreeSet<&str> = NAMED.iter().copied().collect();
        assert_eq!(
            declared, named,
            "FORMATS and the per_format! list disagree: \
             every format needs a named test module, and every module a format"
        );
    }
}

// --------------------------------------------------------------------------
// cross-format invariants
// --------------------------------------------------------------------------

/// Without this, emptying `FORMATS` would make every sweep iterate nothing
/// and pass. A harness that covers no formats must be red, not quiet.
#[test]
fn the_harness_covers_at_least_one_format() {
    assert!(
        !FORMATS.is_empty(),
        "FORMATS is empty, so this harness covers nothing"
    );
}

/// The integer terminal is defined once, and both grammars that need one
/// include that definition rather than spelling it again.
///
/// Two spellings admitting the same strings is the state `regimen` and
/// `record` were in, with a comment in one of them asserting the agreement --
/// and a comment is not a check. Sharing the text removes the divergence;
/// this removes the way it could come back, which is somebody re-inlining
/// the rule into one grammar and leaving the shared file sitting there
/// unread. The parts travel with the terminal because the fractional rules
/// are built out of them.
#[test]
fn the_integer_terminal_is_defined_once_and_shared() {
    const SHARED: &str = "number.pest";
    let root = formats_dir();
    // EVERY `.pest` FILE, not `<dir>/grammar.pest`.
    //
    // The first version joined the literal name, and all eight grammars
    // happened to follow that convention -- so a complete second copy of the
    // three rules, written into `verdict/numbers.pest`, was invisible to this
    // guard and to `cargo test --workspace`, which stayed at 582 passed.
    // Latent rather than live, but only because nobody had added a second
    // `#[grammar]` file yet, and `operating_points.rs` already carries three.
    //
    // The unused second copy is exactly the shape the divergence comes back
    // in: the shared text still sits there, unread, while a grammar spells
    // the rule again.
    let mut grammars: Vec<PathBuf> = files_in_or_empty(&root)
        .into_iter()
        .flat_map(|path| {
            if path.is_dir() {
                files_in_or_empty(&path)
            } else {
                vec![path]
            }
        })
        .filter(|path| path.is_file() && path.extension().is_some_and(|ext| ext == "pest"))
        .collect();
    grammars.retain(|path| *path != root.join(SHARED));
    grammars.sort();
    let shared = root.join(SHARED);
    assert!(
        shared.is_file(),
        "{} is missing, so there is nowhere for the terminal to be defined once",
        shared.display()
    );
    grammars.push(shared.clone());
    assert!(
        grammars.len() > 1,
        "only one grammar was found, so this compares nothing"
    );

    let mut failures = Vec::new();
    let mut users = 0;
    // BOTH TERMINALS. `fraction` and `negative_fraction` joined the shared
    // file on 2026-09-12: `regimen::float` and `record::decimal` were
    // byte-identical modulo the rule name, with not even a comment claiming
    // they agreed. Naming only the integer three here would have left the
    // half that just moved unguarded — which is how the divergence came back
    // the first time.
    for rule in [
        "integer",
        "int_part",
        "nonzero",
        "fraction",
        "negative_fraction",
    ] {
        let defined: Vec<&PathBuf> = grammars
            .iter()
            .filter(|path| defines(&std::fs::read_to_string(path).unwrap_or_default(), rule))
            .collect();
        match defined.as_slice() {
            [only] if **only == shared => {}
            [] => failures.push(format!("`{rule}` is defined in no grammar at all")),
            found => failures.push(format!(
                "`{rule}` is defined in {}; it belongs in {SHARED} and nowhere else",
                found
                    .iter()
                    .map(|path| path.display().to_string())
                    .collect::<Vec<_>>()
                    .join(", ")
            )),
        }
    }
    // AND THE SAME QUESTION ASKED OF THE BODIES, because a copy under a new
    // name is not a copy the name check can see. Measured: re-inline the
    // shared fractional rule into the regimen grammar as `negative_float` and
    // the loop above stays green — it is looking for `negative_fraction`.
    let shared_bodies: BTreeSet<String> =
        rules_of(&std::fs::read_to_string(&shared).unwrap_or_default())
            .into_iter()
            .map(|(_, body)| body)
            .collect();
    assert!(
        !shared_bodies.is_empty(),
        "no rule was read out of {SHARED}, so the body comparison below \
         compares against nothing"
    );

    for path in &grammars {
        if *path == shared {
            continue;
        }
        let text = std::fs::read_to_string(path).unwrap_or_default();
        for (name, body) in rules_of(&text) {
            if shared_bodies.contains(&body) {
                failures.push(format!(
                    "`{name}` in {} has a shared terminal's body written out again; \
                     name it `= @{{ <the shared rule> }}` instead, or the divergence \
                     is back under a new name",
                    path.display()
                ));
            }
        }
        if text
            .lines()
            .any(|line| line.contains("integer") || line.contains("fraction"))
        {
            users += 1;
        }
    }
    assert!(
        users >= 2,
        "fewer than two grammars reference the shared terminal, so sharing it \
         is a file nobody reads"
    );
    report(&failures);
}

/// Whether a grammar line is the DEFINITION of `rule`, rather than a use of
/// it or a mention in a comment.
/// Whether `grammar` defines `rule`, anywhere in it.
///
/// OVER THE WHOLE TEXT, NOT LINE BY LINE. This read one line at a time and
/// asked whether the name and the `=` were both on it -- so
///
///     integer
///       = @{ ("-" ~ ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*) | "0" }
///
/// was a definition pest compiles and this guard could not see. A fresh
/// instance found it by writing exactly that and watching all fifteen checks
/// pass over a tree carrying a second, independently-compiling copy of the
/// terminal this test exists to keep single-sourced. Pest does not care where
/// the newlines are, so neither may the thing that polices it.
///
/// Comments are removed first rather than skipped per line, for the same
/// reason: `// integer` on one line and `= @{ ... }` on the next must not
/// join up into a definition that is not there.
/// Every rule a `.pest` file defines, as `(name, body)` with the body's
/// whitespace collapsed and its comments stripped.
///
/// Bodies, because NAMES ARE NOT ENOUGH. The first version of the shared-
/// terminal guard asked "is this rule defined anywhere but the shared file",
/// which a re-inlined copy under a DIFFERENT NAME walks straight past: put
/// `negative_float` back into the regimen grammar with the shared rule's
/// exact body and nothing notices, because the guard is looking for
/// `negative_fraction`. Measured — the lesion passed the suite.
///
/// That is the same hole this test was hardened for once already, one level
/// along: it globbed one filename, so a copy in `numbers.pest` was invisible;
/// now it named one set of rules, so a copy under a new name was. A guard
/// that enumerates what it knows misses whatever it was not told about, and
/// the body is the thing that actually duplicates.
fn rules_of(grammar: &str) -> Vec<(String, String)> {
    let mut source = String::with_capacity(grammar.len());
    for line in grammar.lines() {
        source.push_str(line.split("//").next().unwrap_or(""));
        source.push('\n');
    }
    let mut found = Vec::new();
    let bytes: Vec<char> = source.chars().collect();
    let mut at = 0;
    while at < bytes.len() {
        if bytes[at] != '=' {
            at += 1;
            continue;
        }
        // The name is the token to the left of the `=`.
        let mut start = at;
        while start > 0 && bytes[start - 1].is_whitespace() {
            start -= 1;
        }
        let end = start;
        while start > 0 && (bytes[start - 1].is_alphanumeric() || bytes[start - 1] == '_') {
            start -= 1;
        }
        if start == end {
            at += 1;
            continue;
        }
        let name: String = bytes[start..end].iter().collect();
        // Then the modifier, then the braced body.
        let mut open = at + 1;
        while open < bytes.len() && bytes[open] != '{' {
            if !bytes[open].is_whitespace() && !"@_$!".contains(bytes[open]) {
                break;
            }
            open += 1;
        }
        if open >= bytes.len() || bytes[open] != '{' {
            at += 1;
            continue;
        }
        let mut depth = 0;
        let mut close = open;
        while close < bytes.len() {
            match bytes[close] {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        break;
                    }
                }
                _ => {}
            }
            close += 1;
        }
        if close >= bytes.len() {
            break;
        }
        let body: String = bytes[open + 1..close].iter().collect();
        found.push((name, body.split_whitespace().collect::<Vec<_>>().join(" ")));
        at = close + 1;
    }
    found
}

fn defines(grammar: &str, rule: &str) -> bool {
    let mut source = String::with_capacity(grammar.len());
    for line in grammar.lines() {
        source.push_str(line.split("//").next().unwrap_or(""));
        source.push('\n');
    }
    let mut rest = source.as_str();
    while let Some(at) = rest.find(rule) {
        let (before, after) = rest.split_at(at);
        let after = &after[rule.len()..];
        // A rule name is a whole token: `int_part` must not be found inside
        // `signed_int_part`, and `integer` must not be found inside
        // `integers`.
        let boundary_left = before
            .chars()
            .next_back()
            .is_none_or(|c| !c.is_alphanumeric() && c != '_');
        let boundary_right = after
            .chars()
            .next()
            .is_none_or(|c| !c.is_alphanumeric() && c != '_');
        if boundary_left && boundary_right && after.trim_start().starts_with('=') {
            return true;
        }
        rest = &rest[at + rule.len()..];
    }
    false
}

/// A format directory on disk that `FORMATS` does not name is a format with
/// no grammar requirement and no fixture requirement at all. Coverage must
/// not be a hand-maintained opinion about what exists.
#[test]
fn no_format_directory_is_undeclared() {
    let root = formats_dir();
    let declared: BTreeSet<&str> = FORMATS.iter().map(|format| format.name).collect();
    let mut failures = Vec::new();

    for entry in files_in_or_empty(&root) {
        if !entry.is_dir() {
            continue;
        }
        let Some(name) = entry.file_name().and_then(std::ffi::OsStr::to_str) else {
            failures.push(format!("{}: unreadable directory name", entry.display()));
            continue;
        };
        if !declared.contains(name) {
            failures.push(format!(
                "{name}: has a directory under formats/ but is absent from FORMATS, \
                 so nothing requires it to have a grammar or fixtures"
            ));
        }
    }

    report(&failures);
}
