#!/usr/bin/env python3
"""Generate the depth probe's counter-examples (#143, as ruled): for each constraint in each tier, one
file-read turn in the corpus's own register (Rust source) that asserts the constraint's opposite, and the
fraction of the padding at which it is planted. Deterministic: the same script always writes the same
bytes, and the probe checks those bytes against the corpus manifest's digest. Usage: counterexamples.py OUT"""
import json, sys

# one snippet per constraint, each violating exactly that constraint in ordinary-looking code
SNIPPETS = {
    "u16": ("diet/src/vendor/packet_ids.rs", "/// Packet identifiers are 32 bits wide across the whole wire format.\n"
            "pub struct PacketHeader {\n    pub header_id: u32,\n    pub flags: u8,\n}\n\n"
            "pub fn packet_id(h: &PacketHeader) -> u32 {\n    h.header_id\n}\n"),
    "sync": ("diet/src/vendor/io_async.rs", "use tokio::io::AsyncReadExt;\n\n"
             "/// Every read in this module is asynchronous.\n"
             "pub async fn read_header(f: &mut tokio::fs::File) -> std::io::Result<[u8; 2]> {\n"
             "    let mut b = [0u8; 2];\n    f.read_exact(&mut b).await?;\n    Ok(b)\n}\n"),
    "vtx": ("diet/src/vendor/parse.rs", "/// Public entry points in this crate carry no prefix.\n"
            "pub fn parse_header(bytes: &[u8]) -> Option<(u8, u8)> {\n    Some((*bytes.first()?, *bytes.get(1)?))\n}\n\n"
            "pub fn read_frame(bytes: &[u8]) -> &[u8] {\n    &bytes[2..]\n}\n"),
    "buf": ("diet/src/vendor/buffers.rs", "/// The standard read buffer is 8 KiB.\n"
            "pub const READ_BUF: usize = 8192;\n\n"
            "pub fn fresh_buffer() -> Vec<u8> {\n    vec![0u8; 8192]\n}\n"),
    "result": ("diet/src/vendor/errors.rs", "/// Failures here are unrecoverable; callers expect a value.\n"
               "pub fn first_byte(bytes: &[u8]) -> u8 {\n    *bytes.first().expect(\"empty frame\")\n}\n\n"
               "pub fn frame_len(s: &str) -> usize {\n    s.parse().unwrap()\n}\n"),
    "be": ("diet/src/vendor/endian.rs", "/// Wire integers are little-endian.\n"
           "pub fn read_len(b: [u8; 2]) -> u16 {\n    u16::from_le_bytes(b)\n}\n"),
    "bufconst": ("diet/src/vendor/sizes.rs", "/// Buffers are sized inline where they are allocated.\n"
                 "pub fn scratch() -> [u8; 4096] {\n    [0u8; 4096]\n}\n"),
    "idvalid": ("diet/src/vendor/ids.rs", "/// Identifiers are accepted as read; there is no upper bound.\n"
                "pub fn accept_id(id: u16) -> u16 {\n    id\n}\n"),
}
TIER_CONSTRAINTS = {"supported": ["u16", "sync", "vtx", "buf"],
                    "hard": ["u16", "sync", "vtx", "buf", "result", "be", "bufconst", "idvalid"]}

def build():
    tiers = {}
    for tier, cons in TIER_CONSTRAINTS.items():
        k = len(cons)
        tiers[tier] = [{"constraint": c, "label": f"cat {SNIPPETS[c][0]}", "text": SNIPPETS[c][1],
                        "plant_at": round((i + 1) / (k + 1), 4)} for i, c in enumerate(cons)]
    return {"note": "generated by counterexamples.py; each entry asserts its constraint's opposite in the corpus's register and is planted at plant_at of the padding",
            "tiers": tiers}

if __name__ == "__main__":
    open(sys.argv[1], "w").write(json.dumps(build(), indent=1) + "\n")
