HTTP/1.1 200 OK
Connection: close
Content-Type: text/event-stream
Server: llama.cpp
Transfer-Encoding: chunked
Access-Control-Allow-Origin: 

1fa
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"role":"assistant","content":null}}],"created":1790892377,"id":"chatcmpl-V0avucERm7KnXgWPPrYFMcR60rYBejKK","model":"Qwen3.6-27B","system_fingerprint":"b0-unknown-dirty","object":"chat.completion.chunk"}

data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":"1"}}],"created":1790892377,"id":"chatcmpl-V0avucERm7KnXgWPPrYFMcR60rYBejKK","model":"Qwen3.6-27B","system_fingerprint":"b0-unknown-dirty","object":"chat.completion.chunk"}


f3
data: {"choices":[{"finish_reason":null,"index":0,"delta":{"content":"1"}}],"created":1790892377,"id":"chatcmpl-V0avucERm7KnXgWPPrYFMcR60rYBejKK","model":"Qwen3.6-27B","system_fingerprint":"b0-unknown-dirty","object":"chat.completion.chunk"}


350
data: {"choices":[{"finish_reason":"stop","index":0,"delta":{}}],"created":1790892377,"id":"chatcmpl-V0avucERm7KnXgWPPrYFMcR60rYBejKK","model":"Qwen3.6-27B","system_fingerprint":"b0-unknown-dirty","object":"chat.completion.chunk"}

data: {"choices":[],"created":1790892377,"id":"chatcmpl-V0avucERm7KnXgWPPrYFMcR60rYBejKK","model":"Qwen3.6-27B","system_fingerprint":"b0-unknown-dirty","object":"chat.completion.chunk","usage":{"completion_tokens":3,"prompt_tokens":42,"total_tokens":45,"prompt_tokens_details":{"cached_tokens":38},"completion_tokens_details":{"reasoning_tokens":0,"visible_tokens":3}},"timings":{"cache_n":38,"prompt_n":4,"prompt_ms":59.1,"prompt_per_token_ms":14.775,"prompt_per_second":67.68189509306261,"predicted_n":3,"predicted_ms":59.759,"predicted_per_token_ms":19.919666666666668,"predicted_per_second":50.20164326712295}}


e
data: [DONE]


0

