#!/usr/bin/env python3
"""Apply lane-declared seeded faults for real, from a pinned registry.

Nine lanes write their own seeded faults beside the code that emits them --
ruling 1 on PR #59 -- as `diet/<lane>/gate.toml`: a `[package]` block naming
the check command, and a `[[fault]]` per mutation, each carrying the exact
source text to replace (`anchor`), what it becomes (`becomes`), the exit code
a run against the mutated tree must produce (`expect_exit`), and the test
names that must be among the failures (`catches`). Every one was GENERATED BY
RUNNING IT once, by hand, when its lane was built.

Once was the whole problem. `tools/gate/lanes.toml` -- the root registry,
"the registry is the pin" per tools/gate/README.md -- names which of those
manifests exist; this script is what applies them continuously rather than
once: `--verify` (this file's `lanes` check) confirms every registered lane
is present and green, `--list` is what `verify.sh --selftest` reads to turn
every declared fault into a seeded case -- one signature per catcher, every
one required (#239) -- and `--apply-only LANE ID` is the
injection that case runs.

THREE THINGS THIS PROVES, RULED ON #76:

  * a registry entry naming a manifest that is not there;
  * a manifest on disk (`diet/*/gate.toml`) with no registry entry;
  * (NOT here -- see `check-fault-manifest.py`) a lane fault this script can
    see that the outer manifest, `tools/gate/faults.toml`, does not
    register. That comparison already lives in the one script whose whole
    job is comparing what a gate proves against what the manifest claims;
    duplicating it here would be a second reader of the same question.

Stdlib only, except `tomllib`. Exit 0 if verified/listed cleanly, 1 if a lane
is not green or the registry has drifted from what is on disk, 2 if the
registry or a manifest could not be read at all -- a scan that could not run
is not a scan that passed.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import shlex
import subprocess
import sys
import tomllib

EXIT_DIRTY = 1
EXIT_BROKEN = 2

HERE = pathlib.Path(__file__).resolve().parent
DEFAULT_ROOT = HERE.parent
DEFAULT_REGISTRY = "tools/gate/lanes.toml"

# Cargo's own failure block: `failures:` then each name indented four spaces,
# ending at a blank line or the summary. The same shape `derive-scopes.py`
# already parses for the same reason -- one format, read the same way
# wherever a test run's own log is the evidence.
FAILURE_NAME = re.compile(r"^\s{4}([A-Za-z_][A-Za-z0-9_:]*)\s*$", re.M)

# Between a fault's signatures in `--list`'s third column, one per catcher.
# The ASCII unit separator: a tab is the column separator, a newline the row
# separator, and neither can sit inside a column. No test path holds one.
SIGNATURE_SEPARATOR = "\x1f"


class Unusable(Exception):
    """The registry or a manifest could not be read at all.

    Its own exception, not `sys.exit(message)`: that form exits ONE, this
    repository's code for "found something", and a registry nobody can read
    is a scan that did not run.
    """


def load_registry(root: pathlib.Path, registry_path: pathlib.Path) -> dict[str, str]:
    try:
        data = tomllib.loads(registry_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as err:
        raise Unusable(f"cannot read {registry_path}: {err}") from err
    lanes = data.get("lanes")
    if not isinstance(lanes, dict) or not lanes:
        raise Unusable(
            f"{registry_path} declares no lanes; a registry of nothing pins nothing"
        )
    for name, rel in lanes.items():
        if not isinstance(rel, str):
            raise Unusable(f"{registry_path}: lane '{name}' names {rel!r}, not a path")
    return lanes


def load_manifest(path: pathlib.Path) -> tuple[dict, list[dict]]:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    if "package" not in data:
        raise Unusable(f"{path} has no [package] block")
    package = data["package"]
    if "command" not in package:
        raise Unusable(f"{path}: [package] names no command")
    # `[]`, not `data["fault"]`: a lane with nothing declared yet is a
    # legitimate, if unlikely, state, and this reader's job is reading the
    # manifest, not asserting it is non-empty -- `--verify` and `--list`
    # decide what to make of zero.
    faults = data.get("fault", [])
    for fault in faults:
        for key in ("id", "target", "anchor", "becomes", "expect_exit", "catches"):
            if key not in fault:
                raise Unusable(f"{path}: fault missing '{key}': {fault.get('id', fault)}")
    return package, faults


def discovered_manifests(root: pathlib.Path) -> set[pathlib.Path]:
    """Every `diet/*/gate.toml` on disk, relative to `root`."""
    return {p.relative_to(root) for p in root.glob("diet/*/gate.toml")}


class Findings:
    """What `--verify` and `--list` both need: the registered lanes that
    could be loaded, and every drift between the registry, the filesystem,
    and each manifest's own shape."""

    def __init__(self, root: pathlib.Path, registry_path: pathlib.Path) -> None:
        self.problems: list[str] = []
        self.lanes: dict[str, tuple[dict, list[dict]]] = {}

        registry = load_registry(root, registry_path)
        registered_paths: set[pathlib.Path] = set()
        for name, rel in sorted(registry.items()):
            rel_path = pathlib.Path(rel)
            registered_paths.add(rel_path)
            full = root / rel_path
            if not full.is_file():
                self.problems.append(
                    f"registry names '{name}' -> {rel}, which is not there"
                )
                continue
            try:
                self.lanes[name] = load_manifest(full)
            except (OSError, tomllib.TOMLDecodeError, Unusable) as err:
                self.problems.append(f"{rel} could not be read as a lane manifest: {err}")

        for found in sorted(discovered_manifests(root)):
            if found not in registered_paths:
                self.problems.append(f"{found} is a lane manifest with no registry entry")


def run_command(command: str, root: pathlib.Path) -> tuple[int, str]:
    try:
        proc = subprocess.run(
            command,
            shell=True,
            cwd=root,
            capture_output=True,
            text=True,
            timeout=600,
        )
    except (OSError, subprocess.TimeoutExpired) as err:
        return -1, str(err)
    return proc.returncode, proc.stdout + proc.stderr


# WHICH LANES A CATCHER RUNS IN (#360, ruled (a) at #360 5977576784). Every
# lane's command is `cargo test ... -- FILTER [--skip NAME]...`, and cargo
# runs a test when FILTER is a substring of its path and no `--skip` is. So a
# catcher -- a test path a fault's `catches` names -- resolves to the set of
# lanes whose registered command selects it by that rule, read from the
# command itself. A lane fault's scope is the union over its catchers; a
# catcher selected by two lanes runs in both. A command this cannot read as
# `cargo test` selects nothing, so a catcher only it could run resolves to no
# lane, and the generated case is WRONG before anything runs.
def lane_selection(command: str) -> tuple[str, list[str]] | None:
    """(filter, skips) from a `cargo test` command; filter "" selects every
    test. None when the command is not `cargo test`."""
    try:
        words = shlex.split(command)
    except ValueError:
        return None
    if words[:2] != ["cargo", "test"]:
        return None
    after = words[words.index("--") + 1:] if "--" in words else []
    filters, skips, i = [], [], 0
    while i < len(after):
        if after[i] == "--skip" and i + 1 < len(after):
            skips.append(after[i + 1]); i += 2; continue
        if not after[i].startswith("-"):
            filters.append(after[i])
        i += 1
    if len(filters) > 1:
        return None
    return (filters[0] if filters else ""), skips


def selects(selection: tuple[str, list[str]] | None, path: str) -> bool:
    if selection is None:
        return False
    flt, skips = selection
    return flt in path and not any(s in path for s in skips)


def lane_scope(catches: list[str], commands: dict[str, str]) -> list[str] | None:
    """The sorted lanes a fault's catchers run in, or None when any catcher
    resolves to no lane."""
    selections = {name: lane_selection(command) for name, command in commands.items()}
    scope: set[str] = set()
    for path in catches:
        lanes = {name for name, sel in selections.items() if selects(sel, path)}
        if not lanes:
            return None
        scope |= lanes
    return sorted(scope)


def lane_fixtures() -> list[str]:
    """Where the resolution is wrong, each said; empty when it is right."""
    wrong = []
    commands = {
        "client": "cargo test -p x -- client --skip every_seeded_fault",
        "drive": "cargo test -p x -- drive --skip every_seeded_fault",
        "digest": "cargo test -p x -- digest:: --skip every_seeded_fault",
        "synthetic": "printf 'not cargo'; exit 1",
    }
    for catches, want in (
        (["drive::serve::tests::a"], ["drive"]),
        # A catcher two filters select runs in both lanes, never one.
        (["drive::client::tests::a"], ["client", "drive"]),
        (["drive::serve::tests::a", "client::tests::b"], ["client", "drive"]),
        (["digest::tests::a"], ["digest"]),
        (["digester::tests::a"], None),
        (["drive::every_seeded_fault_still_names"], None),
        (["nobody::tests::a"], None),
    ):
        got = lane_scope(catches, commands)
        if got != want:
            wrong.append(f"{catches} resolved to {got}, not {want}")
    return wrong


def cmd_verify(root: pathlib.Path, registry_path: pathlib.Path, only: list[str] | None = None) -> int:
    found = Findings(root, registry_path)
    for problem in found.problems:
        print(f"apply-lane-faults: {problem}", file=sys.stderr)
    # A SCOPE (#360): run only the lanes named. A name no lane carries, or no
    # name at all, is a misuse, not a smaller run that passes.
    if only is not None:
        unknown = sorted(set(only) - set(found.lanes))
        if not only or unknown:
            print(f"apply-lane-faults: --lanes names {', '.join(unknown) or 'no lane'}; "
                  f"registered: {', '.join(sorted(found.lanes))}", file=sys.stderr)
            return EXIT_BROKEN

    broken = False
    dirty = False
    total_faults = 0
    total_catchers = 0
    for name, (package, faults) in sorted(found.lanes.items()):
        if only is not None and name not in only:
            continue
        total_faults += len(faults)
        total_catchers += sum(len(f.get("catches") or []) for f in faults)
        rc, log = run_command(package["command"], root)
        if rc == -1:
            print(f"apply-lane-faults: {name}'s command could not run: {log}", file=sys.stderr)
            broken = True
            continue
        if rc != 0:
            print(
                f"apply-lane-faults: {name} is not green ({package['command']!r} "
                f"exited {rc})",
                file=sys.stderr,
            )
            print(log, file=sys.stderr)
            dirty = True

    if broken:
        return EXIT_BROKEN
    if found.problems or dirty:
        return EXIT_DIRTY
    ran = len(found.lanes) if only is None else len(set(only))
    print(
        f"apply-lane-faults: {ran} lane(s) of {len(found.lanes)} registered run and green"
        f"{'' if only is None else ' (' + ', '.join(sorted(set(only))) + ')'}, "
        f"{total_faults} fault(s) declared, {total_catchers} catcher(s) among them"
    )
    return 0


def failure_signature(test_path: str) -> str:
    """The ERE that appears ONLY when `test_path` fails, never when it runs.

    A fresh-instance review of #83 found the third column of `--list` was the
    bare test path -- which `cargo test` also prints on a PASS
    (`test <path> ... ok`), so the selftest's own stated rule
    ("A test NAME is not a signature: cargo test prints it on success too")
    was violated by every lane-generated case, 123 of them. `--verify` (and
    the check the selftest drives, `--only lanes`) captures the lane's
    `cargo test` output verbatim and prints it on a nonzero exit, so the
    line to anchor on is cargo's own failure line: `<path> ... FAILED`,
    which cargo emits for a failing test and never for a passing one.
    """
    return f"{re.escape(test_path)} \\.\\.\\. FAILED"


def cmd_list(root: pathlib.Path, registry_path: pathlib.Path) -> int:
    try:
        found = Findings(root, registry_path)
    except Unusable as err:
        print(f"apply-lane-faults: {err}", file=sys.stderr)
        return EXIT_BROKEN
    for problem in found.problems:
        print(f"apply-lane-faults: {problem}", file=sys.stderr)
    if found.problems:
        return EXIT_DIRTY
    commands = {name: package["command"] for name, (package, _faults) in found.lanes.items()}
    for name, (_package, faults) in sorted(found.lanes.items()):
        for fault in faults:
            catches = fault.get("catches") or []
            if not catches:
                print(
                    # `fault["id"]` is already lane-prefixed (every gate.toml
                    # declares it that way, e.g. "isolation.…"), so `{name}.`
                    # here duplicated the lane rather than naming it -- a
                    # fresh-instance review of #83 found this cosmetic, but
                    # it is the same string every message below repeats.
                    f"apply-lane-faults: {fault['id']} declares no catches",
                    file=sys.stderr,
                )
                return EXIT_BROKEN
            # EVERY catcher, not the first (#239). This column used to carry
            # `catches[0]` alone, so a second catcher that stopped catching
            # was declared in the manifest and never checked anywhere CI
            # runs. The selftest requires each of these in the fault's log.
            print(
                "\t".join(
                    [
                        name,
                        fault["id"],
                        SIGNATURE_SEPARATOR.join(failure_signature(c) for c in catches),
                        fault.get("failure_class", ""),
                        # The lanes its catchers run in (#360), comma-joined;
                        # empty when a catcher resolves to none.
                        ",".join(lane_scope(catches, commands) or []),
                    ]
                )
            )
    return 0


def cmd_apply_only(root: pathlib.Path, registry_path: pathlib.Path, lane: str, fault_id: str) -> int:
    try:
        found = Findings(root, registry_path)
    except Unusable as err:
        print(f"apply-lane-faults: {err}", file=sys.stderr)
        return EXIT_BROKEN
    entry = found.lanes.get(lane)
    if entry is None:
        print(f"apply-lane-faults: no registered lane '{lane}'", file=sys.stderr)
        return EXIT_BROKEN
    _package, faults = entry
    fault = next((f for f in faults if f["id"] == fault_id), None)
    if fault is None:
        print(f"apply-lane-faults: {lane} declares no fault '{fault_id}'", file=sys.stderr)
        return EXIT_BROKEN

    target = root / fault["target"]
    try:
        text = target.read_text(encoding="utf-8")
    except OSError as err:
        print(f"apply-lane-faults: cannot read {target}: {err}", file=sys.stderr)
        return EXIT_BROKEN

    count = text.count(fault["anchor"])
    if count != 1:
        print(
            f"apply-lane-faults: {fault_id}'s anchor appears {count} "
            f"time(s) in {target}, not exactly once",
            file=sys.stderr,
        )
        return EXIT_BROKEN

    try:
        target.write_text(text.replace(fault["anchor"], fault["becomes"], 1), encoding="utf-8")
    except OSError as err:
        print(f"apply-lane-faults: cannot write {target}: {err}", file=sys.stderr)
        return EXIT_BROKEN
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        default=str(DEFAULT_ROOT),
        help="repository root everything else resolves against (default: this "
        "script's own checkout, so a caller that `cd`s into a sandbox before "
        "invoking a RELATIVE path gets that sandbox for free)",
    )
    parser.add_argument(
        "--registry",
        default=None,
        help=f"the root registry (default: <root>/{DEFAULT_REGISTRY})",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--verify", action="store_true", help="run every registered lane's command")
    group.add_argument("--list", action="store_true", help="print lane<TAB>id<TAB>signatures<TAB>class<TAB>scope, one fault per line; the signatures, one per catcher, are joined by the ASCII unit separator; the scope is the lanes its catchers run in, comma-joined, empty when one runs in none")
    group.add_argument("--selftest", action="store_true", help="the lane resolution's fixtures")
    parser.add_argument("--lanes", help="with --verify: only these lanes, comma-joined (#360)")
    group.add_argument(
        "--apply-only",
        nargs=2,
        metavar=("LANE", "ID"),
        help="mutate one fault's target file in place; does not run or revert anything",
    )
    args = parser.parse_args(argv)

    root = pathlib.Path(args.root).resolve()
    registry_path = (
        pathlib.Path(args.registry) if args.registry else root / DEFAULT_REGISTRY
    )

    if args.selftest:
        wrong = lane_fixtures()
        for line in wrong:
            print(f"apply-lane-faults: {line}", file=sys.stderr)
        print(f"apply-lane-faults: lane resolution fixtures, {len(wrong)} wrong")
        return EXIT_DIRTY if wrong else 0
    if args.lanes is not None and not args.verify:
        print("apply-lane-faults: --lanes narrows --verify and nothing else", file=sys.stderr)
        return EXIT_BROKEN
    try:
        if args.verify:
            return cmd_verify(root, registry_path,
                              None if args.lanes is None else [l for l in args.lanes.split(",") if l])
        if args.list:
            return cmd_list(root, registry_path)
        lane, fault_id = args.apply_only
        return cmd_apply_only(root, registry_path, lane, fault_id)
    except Unusable as err:
        print(f"apply-lane-faults: {err}", file=sys.stderr)
        return EXIT_BROKEN


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
