#!/usr/bin/env python3
"""Apply lane-declared seeded faults for real, from a pinned registry.

Nine lanes write their own seeded faults beside the code that emits them --
ruling 1 on PR #59 -- as `diet/<lane>/gate.toml`: a `[package]` block naming
the check command, and a `[[fault]]` per mutation, each carrying the exact
source text to replace (`anchor`), what it becomes (`becomes`), the exit code
a run against the mutated tree must produce (`expect_exit`), and the test
names that must be among the failures (`catches`). Every one was GENERATED BY
RUNNING IT once, by hand, when its lane was built.

Once was the whole problem. `tools/gate/lanes.toml` -- the root registry,
"the registry is the pin" per tools/gate/README.md -- names which of those
manifests exist; this script is what applies them continuously rather than
once: `--verify` (this file's `lanes` check) confirms every registered lane
is present and green, `--list` is what `verify.sh --selftest` reads to turn
every declared fault into a seeded case, and `--apply-only LANE ID` is the
injection that case runs.

THREE THINGS THIS PROVES, RULED ON #76:

  * a registry entry naming a manifest that is not there;
  * a manifest on disk (`diet/*/gate.toml`) with no registry entry;
  * (NOT here -- see `check-fault-manifest.py`) a lane fault this script can
    see that the outer manifest, `tools/gate/faults.toml`, does not
    register. That comparison already lives in the one script whose whole
    job is comparing what a gate proves against what the manifest claims;
    duplicating it here would be a second reader of the same question.

Stdlib only, except `tomllib`. Exit 0 if verified/listed cleanly, 1 if a lane
is not green or the registry has drifted from what is on disk, 2 if the
registry or a manifest could not be read at all -- a scan that could not run
is not a scan that passed.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
import tomllib

EXIT_DIRTY = 1
EXIT_BROKEN = 2

HERE = pathlib.Path(__file__).resolve().parent
DEFAULT_ROOT = HERE.parent
DEFAULT_REGISTRY = "tools/gate/lanes.toml"

# Cargo's own failure block: `failures:` then each name indented four spaces,
# ending at a blank line or the summary. The same shape `derive-scopes.py`
# already parses for the same reason -- one format, read the same way
# wherever a test run's own log is the evidence.
FAILURE_NAME = re.compile(r"^\s{4}([A-Za-z_][A-Za-z0-9_:]*)\s*$", re.M)


class Unusable(Exception):
    """The registry or a manifest could not be read at all.

    Its own exception, not `sys.exit(message)`: that form exits ONE, this
    repository's code for "found something", and a registry nobody can read
    is a scan that did not run.
    """


def load_registry(root: pathlib.Path, registry_path: pathlib.Path) -> dict[str, str]:
    try:
        data = tomllib.loads(registry_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as err:
        raise Unusable(f"cannot read {registry_path}: {err}") from err
    lanes = data.get("lanes")
    if not isinstance(lanes, dict) or not lanes:
        raise Unusable(
            f"{registry_path} declares no lanes; a registry of nothing pins nothing"
        )
    for name, rel in lanes.items():
        if not isinstance(rel, str):
            raise Unusable(f"{registry_path}: lane '{name}' names {rel!r}, not a path")
    return lanes


def load_manifest(path: pathlib.Path) -> tuple[dict, list[dict]]:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    if "package" not in data:
        raise Unusable(f"{path} has no [package] block")
    package = data["package"]
    if "command" not in package:
        raise Unusable(f"{path}: [package] names no command")
    # `[]`, not `data["fault"]`: a lane with nothing declared yet is a
    # legitimate, if unlikely, state, and this reader's job is reading the
    # manifest, not asserting it is non-empty -- `--verify` and `--list`
    # decide what to make of zero.
    faults = data.get("fault", [])
    for fault in faults:
        for key in ("id", "target", "anchor", "becomes", "expect_exit", "catches"):
            if key not in fault:
                raise Unusable(f"{path}: fault missing '{key}': {fault.get('id', fault)}")
    return package, faults


def discovered_manifests(root: pathlib.Path) -> set[pathlib.Path]:
    """Every `diet/*/gate.toml` on disk, relative to `root`."""
    return {p.relative_to(root) for p in root.glob("diet/*/gate.toml")}


class Findings:
    """What `--verify` and `--list` both need: the registered lanes that
    could be loaded, and every drift between the registry, the filesystem,
    and each manifest's own shape."""

    def __init__(self, root: pathlib.Path, registry_path: pathlib.Path) -> None:
        self.problems: list[str] = []
        self.lanes: dict[str, tuple[dict, list[dict]]] = {}

        registry = load_registry(root, registry_path)
        registered_paths: set[pathlib.Path] = set()
        for name, rel in sorted(registry.items()):
            rel_path = pathlib.Path(rel)
            registered_paths.add(rel_path)
            full = root / rel_path
            if not full.is_file():
                self.problems.append(
                    f"registry names '{name}' -> {rel}, which is not there"
                )
                continue
            try:
                self.lanes[name] = load_manifest(full)
            except (OSError, tomllib.TOMLDecodeError, Unusable) as err:
                self.problems.append(f"{rel} could not be read as a lane manifest: {err}")

        for found in sorted(discovered_manifests(root)):
            if found not in registered_paths:
                self.problems.append(f"{found} is a lane manifest with no registry entry")


def run_command(command: str, root: pathlib.Path) -> tuple[int, str]:
    try:
        proc = subprocess.run(
            command,
            shell=True,
            cwd=root,
            capture_output=True,
            text=True,
            timeout=600,
        )
    except (OSError, subprocess.TimeoutExpired) as err:
        return -1, str(err)
    return proc.returncode, proc.stdout + proc.stderr


def cmd_verify(root: pathlib.Path, registry_path: pathlib.Path) -> int:
    found = Findings(root, registry_path)
    for problem in found.problems:
        print(f"apply-lane-faults: {problem}", file=sys.stderr)

    broken = False
    dirty = False
    total_faults = 0
    for name, (package, faults) in sorted(found.lanes.items()):
        total_faults += len(faults)
        rc, log = run_command(package["command"], root)
        if rc == -1:
            print(f"apply-lane-faults: {name}'s command could not run: {log}", file=sys.stderr)
            broken = True
            continue
        if rc != 0:
            print(
                f"apply-lane-faults: {name} is not green ({package['command']!r} "
                f"exited {rc})",
                file=sys.stderr,
            )
            print(log, file=sys.stderr)
            dirty = True

    if broken:
        return EXIT_BROKEN
    if found.problems or dirty:
        return EXIT_DIRTY
    print(
        f"apply-lane-faults: {len(found.lanes)} lane(s) registered and green, "
        f"{total_faults} fault(s) declared"
    )
    return 0


def cmd_list(root: pathlib.Path, registry_path: pathlib.Path) -> int:
    try:
        found = Findings(root, registry_path)
    except Unusable as err:
        print(f"apply-lane-faults: {err}", file=sys.stderr)
        return EXIT_BROKEN
    for problem in found.problems:
        print(f"apply-lane-faults: {problem}", file=sys.stderr)
    if found.problems:
        return EXIT_DIRTY
    for name, (_package, faults) in sorted(found.lanes.items()):
        for fault in faults:
            catches = fault.get("catches") or []
            if not catches:
                print(
                    f"apply-lane-faults: {name}.{fault['id']} declares no catches",
                    file=sys.stderr,
                )
                return EXIT_BROKEN
            print(
                "\t".join(
                    [name, fault["id"], catches[0], fault.get("failure_class", "")]
                )
            )
    return 0


def cmd_apply_only(root: pathlib.Path, registry_path: pathlib.Path, lane: str, fault_id: str) -> int:
    try:
        found = Findings(root, registry_path)
    except Unusable as err:
        print(f"apply-lane-faults: {err}", file=sys.stderr)
        return EXIT_BROKEN
    entry = found.lanes.get(lane)
    if entry is None:
        print(f"apply-lane-faults: no registered lane '{lane}'", file=sys.stderr)
        return EXIT_BROKEN
    _package, faults = entry
    fault = next((f for f in faults if f["id"] == fault_id), None)
    if fault is None:
        print(f"apply-lane-faults: {lane} declares no fault '{fault_id}'", file=sys.stderr)
        return EXIT_BROKEN

    target = root / fault["target"]
    try:
        text = target.read_text(encoding="utf-8")
    except OSError as err:
        print(f"apply-lane-faults: cannot read {target}: {err}", file=sys.stderr)
        return EXIT_BROKEN

    count = text.count(fault["anchor"])
    if count != 1:
        print(
            f"apply-lane-faults: {lane}.{fault_id}'s anchor appears {count} "
            f"time(s) in {target}, not exactly once",
            file=sys.stderr,
        )
        return EXIT_BROKEN

    try:
        target.write_text(text.replace(fault["anchor"], fault["becomes"], 1), encoding="utf-8")
    except OSError as err:
        print(f"apply-lane-faults: cannot write {target}: {err}", file=sys.stderr)
        return EXIT_BROKEN
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        default=str(DEFAULT_ROOT),
        help="repository root everything else resolves against (default: this "
        "script's own checkout, so a caller that `cd`s into a sandbox before "
        "invoking a RELATIVE path gets that sandbox for free)",
    )
    parser.add_argument(
        "--registry",
        default=None,
        help=f"the root registry (default: <root>/{DEFAULT_REGISTRY})",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--verify", action="store_true", help="run every registered lane's command")
    group.add_argument("--list", action="store_true", help="print lane<TAB>id<TAB>signature<TAB>class, one fault per line")
    group.add_argument(
        "--apply-only",
        nargs=2,
        metavar=("LANE", "ID"),
        help="mutate one fault's target file in place; does not run or revert anything",
    )
    args = parser.parse_args(argv)

    root = pathlib.Path(args.root).resolve()
    registry_path = (
        pathlib.Path(args.registry) if args.registry else root / DEFAULT_REGISTRY
    )

    try:
        if args.verify:
            return cmd_verify(root, registry_path)
        if args.list:
            return cmd_list(root, registry_path)
        lane, fault_id = args.apply_only
        return cmd_apply_only(root, registry_path, lane, fault_id)
    except Unusable as err:
        print(f"apply-lane-faults: {err}", file=sys.stderr)
        return EXIT_BROKEN


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
