//! SHA-256: the crate's one digest, and the record's identity primitive.
//!
//! A summary row requires a digest of the product the session produced, and
//! the schema requires it to be sixty-four lowercase hex characters. A drive
//! that could not compute one could not write a summary, and a record without
//! a summary is not a record. The bakeoff runner needs the same primitive to
//! hold its inputs to the digests they declare. So this is on the critical
//! path rather than a convenience -- and it is at the CRATE ROOT because two
//! lanes consume it. A bakeoff reaching into `drive::` for its hashing is the
//! shape the root placement was ruled to prevent.
//!
//! # One implementation, and it is not ours
//!
//! This module hand-rolled the algorithm once. So did the runner verb's lane,
//! independently, in the same week -- two SHA-256s in one crate, each argued
//! for in the same words: *one function of eighty lines is a smaller thing to
//! own than a supply chain.* Both were correct. **That was never the
//! argument.** Ruling 7: a cryptographic primitive is the canonical buy, and
//! the digest is the record's IDENTITY primitive -- binary provenance,
//! consumed digests, engine identity -- which makes it the one place a subtle
//! bug is both catastrophic and silent. A hash somebody wrote in an afternoon
//! is a hash somebody has to keep checking, and the cost of being wrong here
//! is every claim ever banked against a digest.
//!
//! # Three checks on the dependency, and none of them is spare
//!
//! A bought primitive still has to be shown to be that primitive. The tests
//! below divide that job, and the division is the point, because each is
//! blind to what the others catch:
//!
//! * `the_published_vectors_are_what_comes_out` is the FLOOR. The four
//!   vectors FIPS 180-4 publishes, written into the test, answerable from the
//!   standard itself by anyone who doubts the rest of this file.
//! * `the_committed_vectors_are_what_comes_out` is the PORTABLE one, and it
//!   is what a host with no reference implementation actually runs. Two
//!   hundred and twelve inputs and their answers, frozen in
//!   `diet/digest/vectors.tsv` -- the differential's own input set, so the
//!   portable check is no longer the weak one. **Generated by `sha256sum`,
//!   never by `sha2`**: a vector file produced from the crate under test
//!   would agree with it by construction and prove nothing.
//! * `the_dependency_agrees_with_the_system_on_every_shape_that_breaks_a_sha256`
//!   is the LIVE one, and it does two jobs. It differentials `sha2` against
//!   the host's own `sha256sum` -- catching a version bump that changes
//!   behaviour, a feature flag that swaps an implementation, or a build where
//!   the crate is not what the lockfile says -- and, on the same run, it
//!   rechecks the frozen answers against that independent implementation. A
//!   vector file nobody rechecks can be wrong in one direction forever. It
//!   DECLARES a host requirement and fails loudly where that requirement is
//!   absent; it does not skip, for the reasons written on it.
//!
//! Only the hex encoding and the spec decoder are ours, and both are tested
//! like they are ours.

use sha2::{Digest as _, Sha256};

/// The SHA-256 of `bytes`, as sixty-four lowercase hex characters.
///
/// The spelling is the one the record requires, so no caller has to remember
/// to lowercase it -- a digest that differs from the same digest by case is
/// the kind of mismatch that gets debugged for an hour.
#[must_use]
pub fn sha256_hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(64);
    for byte in sha256(bytes) {
        // Written rather than formatted through a width specifier, because a
        // missing zero pad is the classic way a hex encoder produces a digest
        // that is right for most inputs. This half is ours, so it is tested
        // like it is ours.
        out.push(nibble(byte >> 4));
        out.push(nibble(byte & 0x0f));
    }
    out
}

/// One hex digit, lowercase.
fn nibble(value: u8) -> char {
    char::from_digit(u32::from(value), 16).expect("a nibble is below sixteen")
}

/// The SHA-256 of `bytes`, as thirty-two bytes.
#[must_use]
pub fn sha256(bytes: &[u8]) -> [u8; 32] {
    Sha256::digest(bytes).into()
}

#[cfg(test)]
mod tests {

    use super::{sha256, sha256_hex};

    /// The committed known-answer set. See the file's own header for how it
    /// was generated and why it is not generated from `sha2`.
    const VECTORS: &str = include_str!("../digest/vectors.tsv");

    /// The vectors FIPS 180-4 publishes, and the empty message.
    ///
    /// **This is the floor.** Four vectors is thin for a portable check, which
    /// is why `the_committed_vectors_are_what_comes_out` exists beside it --
    /// but these four are the ones a reader can verify against the published
    /// standard without trusting anything in this repository, including the
    /// program that generated the committed set. That is a different kind of
    /// evidence and it is worth keeping separately.
    ///
    /// Kept from the hand-rolled version. They no longer prove this module's
    /// arithmetic -- there is none -- but they are what says the dependency
    /// is computing SHA-256 and not something else that also returns 32
    /// bytes. B.3 is a million bytes and worth its cost: it is the only
    /// vector here that drives the compression function through more than
    /// two blocks.
    #[test]
    fn the_published_vectors_are_what_comes_out() {
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            sha256_hex(b"abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
            "FIPS 180-4 B.1"
        );
        assert_eq!(
            sha256_hex(b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
            "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1",
            "FIPS 180-4 B.2, 56 bytes: the length field lands in a second block"
        );
        assert_eq!(
            sha256_hex(&vec![b'a'; 1_000_000]),
            "cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0",
            "FIPS 180-4 B.3, a million `a`s"
        );
    }

    #[test]
    fn the_spelling_is_the_one_the_record_requires() {
        // The hex encoding is this module's own code, so it is tested as this
        // module's own code. The zero pad is the classic defect: a digest with
        // a byte below 0x10 comes out sixty-three characters long without it.
        let hex = sha256_hex(b"anything");
        assert_eq!(hex.len(), 64, "sixty-four characters, always");
        assert!(
            hex.chars()
                .all(|c| c.is_ascii_digit() || ('a'..='f').contains(&c)),
            "lowercase hex and nothing else: {hex}"
        );
        let padded = sha256(b"5040");
        assert!(
            padded.iter().any(|byte| *byte < 0x10),
            "the fixture has a byte that needs the pad: {padded:?}"
        );
        assert_eq!(sha256_hex(b"5040").len(), 64);
    }

    /// The committed known-answer set: every `(spec, digest)` the file holds.
    ///
    /// One reader, used by both the portable test and the differential, so
    /// the two cannot drift into checking different inputs.
    fn committed() -> Vec<(&'static str, &'static str)> {
        VECTORS
            .lines()
            .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
            .map(|line| {
                line.split_once('\t')
                    .unwrap_or_else(|| panic!("a vector line is `<spec>\\t<digest>`: {line}"))
            })
            .collect()
    }

    /// The count the file DECLARES, read rather than written down here.
    ///
    /// The same law the fault manifests follow. Hardcoded in the test, a line
    /// deleted from the file would take the assertion with it and pass.
    fn declared() -> usize {
        let line = VECTORS
            .lines()
            .find_map(|line| line.strip_prefix("# vectors = "))
            .expect("the file declares how many vectors it holds");
        line.trim()
            .parse()
            .unwrap_or_else(|why| panic!("the declared count is not a number: {why}"))
    }

    /// The bytes a spec stands for.
    ///
    /// Two forms and no more. `hex:<hex>` is literal bytes; `rep:<hex
    /// byte>:<count>` is one byte repeated, which is why a hundred thousand
    /// identical bytes cost one short line instead of a megabyte of hex.
    fn decode(spec: &str) -> Vec<u8> {
        if let Some(hex) = spec.strip_prefix("hex:") {
            assert!(hex.len() % 2 == 0, "`{spec}` has half a byte in it");
            return hex
                .as_bytes()
                .chunks(2)
                .map(|pair| {
                    let pair = std::str::from_utf8(pair).expect("the file is ASCII");
                    u8::from_str_radix(pair, 16)
                        .unwrap_or_else(|why| panic!("`{spec}` is not hex: {why}"))
                })
                .collect();
        }
        let rest = spec
            .strip_prefix("rep:")
            .unwrap_or_else(|| panic!("`{spec}` is neither `hex:` nor `rep:`"));
        let (byte, count) = rest
            .split_once(':')
            .unwrap_or_else(|| panic!("`{spec}` is `rep:<hex byte>:<count>`"));
        let byte = u8::from_str_radix(byte, 16)
            .unwrap_or_else(|why| panic!("`{spec}` names no byte: {why}"));
        let count: usize = count
            .parse()
            .unwrap_or_else(|why| panic!("`{spec}` names no count: {why}"));
        vec![byte; count]
    }

    /// The decoder is ours, so it is tested like it is ours.
    ///
    /// The committed digests were produced from bytes a DIFFERENT decoder
    /// staged -- the generator's, in another language. A disagreement between
    /// the two would fail every vector at once, loudly. What that would not
    /// catch is the two being wrong the same way, so these cases are checked
    /// against the bytes by eye rather than against the generator.
    #[test]
    fn a_spec_decodes_to_the_bytes_it_names() {
        assert_eq!(decode("hex:616263"), b"abc");
        assert_eq!(decode("hex:"), b"");
        assert_eq!(decode("hex:00ff"), [0x00, 0xff]);
        assert_eq!(decode("rep:61:3"), b"aaa");
        assert_eq!(decode("rep:61:0"), b"");
        assert_eq!(decode("rep:ff:2"), [0xff, 0xff]);

        let vectors = committed();
        assert_eq!(
            vectors.len(),
            declared(),
            "the file declares its own count and this reads it"
        );
        assert!(
            vectors.iter().all(|(_, digest)| digest.len() == 64
                && digest
                    .chars()
                    .all(|c| c.is_ascii_digit() || ('a'..='f').contains(&c))),
            "every committed answer is sixty-four lowercase hex characters"
        );
    }

    /// The portable check, and the one a host without `sha256sum` runs.
    ///
    /// Ruling on #71's fourth disclosure: the differential's value should not
    /// depend on a host binary being present, so its input set is frozen here
    /// with answers an independent implementation produced. The four
    /// published vectors above stay as the floor.
    ///
    /// This cannot catch a committed answer that was wrong when it was
    /// written -- nothing that reads only this file can. That is the
    /// differential's second job.
    #[test]
    fn the_committed_vectors_are_what_comes_out() {
        let vectors = committed();
        assert_eq!(vectors.len(), declared());
        assert!(
            !vectors.is_empty(),
            "a known-answer test with no answers in it is not a check"
        );
        for (at, (spec, want)) in vectors.iter().enumerate() {
            let bytes = decode(spec);
            assert_eq!(
                &sha256_hex(&bytes),
                want,
                "committed vector {at} (`{spec}`, {} bytes) is not what came out",
                bytes.len()
            );
        }
    }

    /// An independent SHA-256, for the differential below to compare against.
    ///
    /// `sha256sum` on a GNU host, `shasum -a 256` on a Mac -- this repository
    /// has seats on both. Both print `<digest>  <path>`, so the caller reads
    /// them the same way.
    ///
    /// Returns the program and the arguments that precede the paths.
    fn an_independent_sha256() -> Option<(&'static str, &'static [&'static str])> {
        for (program, args) in [
            ("sha256sum", &[] as &[&str]),
            ("shasum", &["-a", "256"] as &[&str]),
        ] {
            let answered = std::process::Command::new(program)
                .args(args)
                .arg("--version")
                .output()
                .is_ok_and(|probe| probe.status.success());
            if answered {
                return Some((program, args));
            }
        }
        None
    }

    /// The differential: the ADDITIONAL check, not the portable one.
    ///
    /// A fresh instance ran this by hand while the algorithm was hand-rolled,
    /// as a proof of our arithmetic. Ruling 7 kept it and changed what it is
    /// for: it is now a **conformance check on `sha2`** -- what catches a
    /// version bump that changes behaviour, a feature flag that swaps an
    /// implementation, or a build where the crate is not what the lockfile
    /// says. The published vectors above cannot catch those on their own,
    /// because a wrong implementation that still gets `abc` right is exactly
    /// what a vector set is blind to. That is why both tests exist and why
    /// neither replaces the other.
    ///
    /// **The set is built from named groups and its size is whatever they
    /// come to.** The reviewer's run was 221 inputs and this was very nearly
    /// named for that number -- which would have meant padding the set until
    /// it reached 221, fitting the evidence to the label. What each group is
    /// for is written beside it instead.
    ///
    /// # It has no skip, and that is the whole point
    ///
    /// The first version had THREE early returns -- no temp directory, a
    /// staging write that failed, no `sha256sum` -- each returning a
    /// **passing** test. A review closed one of them and left two, under a
    /// comment claiming the class was handled; `TMPDIR` pointed anywhere
    /// unwritable then retired the entire check, took its own seeded fault
    /// green with it, and let a deliberately corrupted digest through. And
    /// the `eprintln!` those paths announced themselves with is swallowed by
    /// libtest on a passing test, so the log could not tell a run that
    /// differentiated from one that did not.
    ///
    /// So there is no skip at all. **This test declares a host requirement:
    /// an independent SHA-256 must be on `PATH`.** A conformance check that
    /// cannot reach its reference implementation has not been performed, and
    /// a green test that did not perform its check is the failure this whole
    /// module is about. Every seat this repository has -- GNU and Mac -- ships
    /// one of the two programs above.
    #[test]
    fn the_dependency_agrees_with_the_system_on_every_shape_that_breaks_a_sha256() {
        // The inputs are the COMMITTED set's, decoded from the file the
        // portable test reads. One list, so the two checks cannot drift into
        // testing different things -- and so this run is also in a position
        // to say whether the frozen ANSWERS are still right, which it does
        // below. The named groups and what each is for now live in the file's
        // own comments, beside the vectors they produced.
        let vectors = committed();
        let inputs: Vec<Vec<u8>> = vectors.iter().map(|(spec, _)| decode(spec)).collect();

        let (program, prefix) = an_independent_sha256().expect(
            "this test needs an independent SHA-256 on PATH -- `sha256sum` or \
             `shasum` -- to compare `sha2` against. It does not skip when one is \
             absent: a conformance check that cannot reach its reference \
             implementation has not been performed, and a green test that did \
             not perform its check is the defect this module exists to prevent.",
        );

        // Through FILES rather than a pipe. An earlier version fed hex on
        // stdin and decoded it with `xxd`, which is not on every host -- and
        // its absence did not surface as "the tool is missing", it surfaced
        // as a DIGEST MISMATCH on input 1, which is a red that is not about
        // its own fault.
        let ours: Vec<String> = inputs.iter().map(|bytes| sha256_hex(bytes)).collect();
        // Unique per run, and `create_dir` rather than `create_dir_all` so an
        // existing directory is an error rather than something to write into:
        // a predictable name a local process can pre-create, plus writes that
        // follow symlinks, is CWE-377 even in a test.
        let base = std::env::temp_dir().join(format!(
            "diet-digest-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|since| since.as_nanos())
                .unwrap_or_default()
        ));
        std::fs::create_dir(&base).expect("a temp directory to stage the inputs in");
        let mut paths = Vec::with_capacity(inputs.len());
        for (at, bytes) in inputs.iter().enumerate() {
            let path = base.join(format!("{at:04}.bin"));
            std::fs::write(&path, bytes).expect("the inputs stage");
            paths.push(path);
        }

        let spawned = std::process::Command::new(program)
            .args(prefix)
            .args(&paths)
            .output();
        let _ = std::fs::remove_dir_all(&base);
        let output = spawned.unwrap_or_else(|why| {
            panic!("`{program}` answered a probe and then could not be run: {why}")
        });
        assert!(
            output.status.success(),
            "`{program}` itself failed, which is not a disagreement about a \
             digest: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        let theirs: Vec<String> = String::from_utf8_lossy(&output.stdout)
            .lines()
            .filter_map(|line| line.split_whitespace().next())
            .map(str::to_owned)
            .collect();

        assert_eq!(
            theirs.len(),
            inputs.len(),
            "`{program}` answered for every one of the {} inputs, or this \
             compares two lists that are not aligned",
            inputs.len()
        );
        for (at, (ours, theirs)) in ours.iter().zip(&theirs).enumerate() {
            assert_eq!(
                ours,
                theirs,
                "input {at} ({} bytes) disagrees with `{program}`'s digest",
                inputs[at].len()
            );
        }

        // The differential's second job, and the reason the frozen file is
        // safe to lean on. The loop above proves the DEPENDENCY agrees with
        // an independent implementation; this proves the COMMITTED ANSWERS
        // do. Nothing that reads only `vectors.tsv` can check that, so a
        // vector file nobody rechecks is one that can be wrong in a single
        // direction forever -- and it would take the portable test with it,
        // silently, because the two would agree.
        for (at, ((spec, frozen), theirs)) in vectors.iter().zip(&theirs).enumerate() {
            assert_eq!(
                frozen, theirs,
                "committed vector {at} (`{spec}`) no longer agrees with `{program}`. \
                 The file is stale or was wrong when it was written; regenerate it \
                 from an independent implementation rather than from `sha2`."
            );
        }
    }

    /// Every fault in this lane's `gate.toml` still names source that is there.
    ///
    /// The digest is its own lane now that it is at the crate root: its
    /// mutations are not the drive's, and a manifest that claimed them would
    /// be naming a file its lane does not own.
    #[test]
    fn every_seeded_fault_still_names_source_that_is_there() {
        crate::gate::every_seeded_fault_still_names_source(
            include_str!("../digest/gate.toml"),
            // One file, because that is the whole lane.
            include_str!("digest.rs"),
            "digest",
        );
    }
}
