//! SHA-256: the crate's one digest, and the record's identity primitive.
//!
//! A summary row requires a digest of the product the session produced, and
//! the schema requires it to be sixty-four lowercase hex characters. A drive
//! that could not compute one could not write a summary, and a record without
//! a summary is not a record. The bakeoff runner needs the same primitive to
//! hold its inputs to the digests they declare. So this is on the critical
//! path rather than a convenience -- and it is at the CRATE ROOT because two
//! lanes consume it. A bakeoff reaching into `drive::` for its hashing is the
//! shape the root placement was ruled to prevent.
//!
//! # One implementation, and it is not ours
//!
//! This module hand-rolled the algorithm once. So did the runner verb's lane,
//! independently, in the same week -- two SHA-256s in one crate, each argued
//! for in the same words: *one function of eighty lines is a smaller thing to
//! own than a supply chain.* Both were correct. **That was never the
//! argument.** Ruling 7: a cryptographic primitive is the canonical buy, and
//! the digest is the record's IDENTITY primitive -- binary provenance,
//! consumed digests, engine identity -- which makes it the one place a subtle
//! bug is both catastrophic and silent. A hash somebody wrote in an afternoon
//! is a hash somebody has to keep checking, and the cost of being wrong here
//! is every claim ever banked against a digest.
//!
//! # Three checks on the dependency, and none of them is spare
//!
//! A bought primitive still has to be shown to be that primitive. The tests
//! below divide that job, and the division is the point, because each is
//! blind to what the others catch:
//!
//! * `the_published_vectors_are_what_comes_out` is the FLOOR. The four
//!   vectors FIPS 180-4 publishes, written into the test, answerable from the
//!   standard itself by anyone who doubts the rest of this file.
//! * `the_committed_vectors_are_what_comes_out` is the PORTABLE one. It runs
//!   the differential's own input set -- built in `cases`, where a claim
//!   about which inputs are covered cannot be edited away -- against answers
//!   frozen in `diet/digest/vectors.tsv`. **Those answers were generated by
//!   `sha256sum`, never by `sha2`**: a vector file produced from the crate
//!   under test agrees with it by construction and proves nothing.
//!
//!   To be exact about what it buys, since a ruling is being applied here:
//!   on a host with no reference implementation the suite is red anyway,
//!   because the differential declares a hard requirement. What this adds
//!   there is a SIGNAL -- which input disagreed, and how -- where before
//!   there was one failing test saying only that a program was missing.
//! * `the_dependency_agrees_with_the_system_on_every_shape_that_breaks_a_sha256`
//!   is the LIVE one, and it does two jobs. It differentials `sha2` against
//!   the host's own `sha256sum` -- catching a version bump that changes
//!   behaviour, a feature flag that swaps an implementation, or a build where
//!   the crate is not what the lockfile says -- and, on the same run, it
//!   rechecks the frozen answers against that independent implementation. A
//!   vector file nobody rechecks can be wrong in one direction forever. It
//!   DECLARES a host requirement and fails loudly where that requirement is
//!   absent; it does not skip, for the reasons written on it.
//!
//! Only the hex encoding and the spec decoder are ours, and both are tested
//! like they are ours.

use sha2::{Digest as _, Sha256};

/// The SHA-256 of `bytes`, as sixty-four lowercase hex characters.
///
/// The spelling is the one the record requires, so no caller has to remember
/// to lowercase it -- a digest that differs from the same digest by case is
/// the kind of mismatch that gets debugged for an hour.
#[must_use]
pub fn sha256_hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(64);
    for byte in sha256(bytes) {
        // Written rather than formatted through a width specifier, because a
        // missing zero pad is the classic way a hex encoder produces a digest
        // that is right for most inputs. This half is ours, so it is tested
        // like it is ours.
        out.push(nibble(byte >> 4));
        out.push(nibble(byte & 0x0f));
    }
    out
}

/// One hex digit, lowercase.
fn nibble(value: u8) -> char {
    char::from_digit(u32::from(value), 16).expect("a nibble is below sixteen")
}

/// The SHA-256 of `bytes`, as thirty-two bytes.
#[must_use]
pub fn sha256(bytes: &[u8]) -> [u8; 32] {
    Sha256::digest(bytes).into()
}

#[cfg(test)]
mod tests {

    use super::{sha256, sha256_hex};

    /// The committed known-answer set. See the file's own header for how it
    /// was generated and why it is not generated from `sha2`.
    const VECTORS: &str = include_str!("../digest/vectors.tsv");

    /// The vectors FIPS 180-4 publishes, and the empty message.
    ///
    /// **This is the floor.** Four vectors is thin for a portable check, which
    /// is why `the_committed_vectors_are_what_comes_out` exists beside it --
    /// but these four are the ones a reader can verify against the published
    /// standard without trusting anything in this repository, including the
    /// program that generated the committed set. That is a different kind of
    /// evidence and it is worth keeping separately.
    ///
    /// Kept from the hand-rolled version. They no longer prove this module's
    /// arithmetic -- there is none -- but they are what says the dependency
    /// is computing SHA-256 and not something else that also returns 32
    /// bytes. B.3 is a million bytes and worth its cost: it is the only
    /// vector here that drives the compression function through more than
    /// two blocks.
    #[test]
    fn the_published_vectors_are_what_comes_out() {
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            sha256_hex(b"abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
            "FIPS 180-4 B.1"
        );
        assert_eq!(
            sha256_hex(b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
            "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1",
            "FIPS 180-4 B.2, 56 bytes: the length field lands in a second block"
        );
        assert_eq!(
            sha256_hex(&vec![b'a'; 1_000_000]),
            "cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0",
            "FIPS 180-4 B.3, a million `a`s"
        );
    }

    #[test]
    fn the_spelling_is_the_one_the_record_requires() {
        // The hex encoding is this module's own code, so it is tested as this
        // module's own code. The zero pad is the classic defect: a digest with
        // a byte below 0x10 comes out sixty-three characters long without it.
        let hex = sha256_hex(b"anything");
        assert_eq!(hex.len(), 64, "sixty-four characters, always");
        assert!(
            hex.chars()
                .all(|c| c.is_ascii_digit() || ('a'..='f').contains(&c)),
            "lowercase hex and nothing else: {hex}"
        );
        let padded = sha256(b"5040");
        assert!(
            padded.iter().any(|byte| *byte < 0x10),
            "the fixture has a byte that needs the pad: {padded:?}"
        );
        assert_eq!(sha256_hex(b"5040").len(), 64);
    }

    /// The cases: the named groups, built IN CODE, each with the spec that
    /// labels it.
    ///
    /// A review of this file's first version caught why it has to be this way
    /// round. With the specs in the vector file as well as the answers, the
    /// SET was editable: the eight lines carrying the groups that give this
    /// check its teeth -- the second block's padding boundary, embedded NULs,
    /// high bytes with no ASCII -- could be replaced with eight more
    /// `rep:61:n` lines carrying correct digests, and every test stayed green
    /// because the count was still right. A claim about WHICH inputs are
    /// covered cannot live in the file the check reads for its inputs.
    ///
    /// So the file freezes the one thing that cannot be derived here -- the
    /// ANSWERS, which came from an implementation that is not `sha2` -- and
    /// the inputs are constructed, where they cannot be partially true.
    fn cases() -> Vec<(String, Vec<u8>)> {
        let mut cases: Vec<(String, Vec<u8>)> = Vec::new();
        // Every length to 200: spans the one-block and two-block padding
        // cases many times over, and includes 55/56 and 63/64/65 where the
        // length field crosses a block boundary.
        cases.extend((0..=200_usize).map(|n| (format!("rep:61:{n}"), vec![b'a'; n])));
        // 119/120/121, which the published vectors miss: the SECOND block's
        // own padding boundary.
        cases.extend((119..=121_usize).map(|n| (format!("rep:7a:{n}"), vec![b'z'; n])));
        // Every byte value. This is the group that catches a masked high bit,
        // which all four published vectors are blind to because all four are
        // ASCII -- the lane seeds exactly that fault.
        cases.push(labelled(&(0..=255_u8).collect::<Vec<u8>>()));
        // Embedded NULs, at a block boundary and across one.
        cases.extend([64_usize, 65].map(|n| (format!("rep:00:{n}"), vec![0_u8; n])));
        // High bytes with no ASCII at all, at three lengths.
        cases.extend([60_usize, 64, 200].map(|n| (format!("rep:ff:{n}"), vec![0xff_u8; n])));
        // A real product, which is what this function is actually called on.
        cases.push(labelled(b"the product a drive produced\nline two\n"));
        // Bigger than any block count the loops above reach.
        cases.push(("rep:71:100003".to_owned(), vec![b'q'; 100_003]));
        cases
    }

    /// A `hex:` case, spelled from the bytes rather than typed out.
    ///
    /// Through `format!` rather than this module's own `nibble`, so the label
    /// a case carries does not depend on the encoder the case is testing.
    fn labelled(bytes: &[u8]) -> (String, Vec<u8>) {
        use std::fmt::Write as _;
        let mut spec = String::from("hex:");
        for byte in bytes {
            write!(spec, "{byte:02x}").expect("writing to a String cannot fail");
        }
        (spec, bytes.to_vec())
    }

    /// The committed answers, `(spec, digest)`, read from the text of the file.
    ///
    /// Takes its text rather than reaching for the `const`, so the refusals
    /// below can be proved against fixtures. `crate::gate` states the reason
    /// in its own doc -- a checker nothing checks is the thing this repository
    /// does not ship -- and this reader feeds the only conformance check on
    /// `sha2` that runs on every host.
    fn committed(text: &str) -> Vec<(&str, &str)> {
        let mut answers = Vec::new();
        for line in text.lines() {
            if line.starts_with('#') || line.trim().is_empty() {
                continue;
            }
            // Exactly two fields. An earlier version took the first two and
            // ignored the rest, so a line with a stray tab parsed with a
            // digest of `"AA\tXX"` -- refused later by a length check, in a
            // message about the wrong thing.
            let mut fields = line.split('\t');
            let (Some(spec), Some(digest), None) = (fields.next(), fields.next(), fields.next())
            else {
                panic!("a vector line is `<spec>\\t<digest>` and nothing else: {line:?}");
            };
            answers.push((spec, digest));
        }
        answers
    }

    /// The bytes a spec stands for.
    ///
    /// Two forms and no more. `hex:<hex>` is literal bytes; `rep:<hex
    /// byte>:<count>` is one byte repeated, which is why a hundred thousand
    /// identical bytes cost one short line instead of a megabyte of hex.
    ///
    /// This is what makes the committed file readable on its own: anyone can
    /// take a line and recover the input its answer is for, without this
    /// crate. The tests use it to prove each case's label honest.
    fn decode(spec: &str) -> Vec<u8> {
        if let Some(hex) = spec.strip_prefix("hex:") {
            assert!(hex.len() % 2 == 0, "`{spec}` has half a byte in it");
            return hex
                .as_bytes()
                .chunks(2)
                .map(|pair| {
                    // Lowercase hex and nothing else. `from_str_radix` alone
                    // accepts a leading `+` and accepts uppercase, so `+0+f`
                    // and `0F` would both alias to bytes the file's own
                    // format says they are not.
                    assert!(
                        pair.iter()
                            .all(|c| c.is_ascii_digit() || (b'a'..=b'f').contains(c)),
                        "`{spec}` is not lowercase hex"
                    );
                    let pair = std::str::from_utf8(pair).expect("ASCII was just checked");
                    u8::from_str_radix(pair, 16).expect("two lowercase hex digits are a byte")
                })
                .collect();
        }
        let rest = spec
            .strip_prefix("rep:")
            .unwrap_or_else(|| panic!("`{spec}` is neither `hex:` nor `rep:`"));
        let (byte, count) = rest
            .split_once(':')
            .unwrap_or_else(|| panic!("`{spec}` is `rep:<hex byte>:<count>`"));
        assert!(
            byte.len() == 2
                && byte
                    .bytes()
                    .all(|c| c.is_ascii_digit() || (b'a'..=b'f').contains(&c)),
            "`{spec}` names no byte"
        );
        let byte = u8::from_str_radix(byte, 16).expect("two lowercase hex digits are a byte");
        let count: usize = count
            .parse()
            .unwrap_or_else(|why| panic!("`{spec}` names no count: {why}"));
        // Bounded, so a corrupted count aborts on nothing. An allocation
        // failure kills the process without a panic, and the gate reads that
        // as a different exit code than the 101 every seeded fault declares.
        assert!(
            count <= 1_000_000,
            "`{spec}` asks for more bytes than any case needs"
        );
        vec![byte; count]
    }

    /// The decoder and the reader are ours, so they are tested like they are ours.
    #[test]
    fn a_spec_decodes_to_the_bytes_it_names() {
        // Checked against the bytes by eye. The committed answers were
        // produced from bytes the GENERATOR's decoder staged, in another
        // language; a disagreement between the two fails every vector at
        // once, but the two being wrong the same way would be silent, and
        // only reading these by hand catches that.
        assert_eq!(decode("hex:616263"), b"abc");
        assert_eq!(decode("hex:"), b"");
        assert_eq!(decode("hex:00ff"), [0x00, 0xff]);
        assert_eq!(decode("rep:61:3"), b"aaa");
        assert_eq!(decode("rep:61:0"), b"");
        assert_eq!(decode("rep:ff:2"), [0xff, 0xff]);
    }

    /// Every way the vector file can be malformed, refused.
    #[test]
    fn a_malformed_vector_file_is_refused_rather_than_half_read() {
        assert_eq!(
            committed("# a comment\n\n   \nrep:61:1\tca97\n"),
            vec![("rep:61:1", "ca97")],
            "comments, blank lines and whitespace-only lines are skipped"
        );
        for bad in [
            "rep:61:1\tca97\tand-a-third-field\n",
            "rep:61:1 ca97\n",
            "rep:61:1\n",
        ] {
            let why = std::panic::catch_unwind(|| committed(bad))
                .expect_err("a line that is not `<spec>\\t<digest>` is refused");
            let why = why
                .downcast_ref::<String>()
                .map_or("", String::as_str)
                .to_owned();
            assert!(
                why.contains("and nothing else"),
                "the refusal names the shape it wanted: {why}"
            );
        }
    }

    /// The portable check, and the one a host with no `sha256sum` still runs.
    ///
    /// Ruling on #71's fourth disclosure: the differential's value should not
    /// depend on a host binary being present. The four published vectors
    /// above stay as the floor.
    ///
    /// Both directions are checked. Every case has an answer here, and the
    /// file carries no answer no case names -- so a line nobody covers cannot
    /// sit in the file looking like evidence, and a case cannot quietly lose
    /// its answer.
    ///
    /// What this cannot catch is an answer that was wrong when it was
    /// written. Nothing that reads only this file can. That is the
    /// differential's second job.
    #[test]
    fn the_committed_vectors_are_what_comes_out() {
        let cases = cases();
        let answers = committed(VECTORS);
        assert!(
            !cases.is_empty(),
            "a known-answer test with no answers in it is not a check"
        );

        let held: std::collections::BTreeMap<&str, &str> = answers.iter().copied().collect();
        assert_eq!(
            held.len(),
            answers.len(),
            "the file names no spec twice; a duplicate would let one line \
             shadow another and go unchecked"
        );

        for (at, (spec, bytes)) in cases.iter().enumerate() {
            assert_eq!(
                &decode(spec),
                bytes,
                "case {at}: the spec `{spec}` does not name the bytes it labels"
            );
            let want = held
                .get(spec.as_str())
                .unwrap_or_else(|| panic!("case {at}: the file has no answer for `{spec}`"));
            assert_eq!(
                &sha256_hex(bytes),
                want,
                "case {at} (`{spec}`, {} bytes) is not what came out",
                bytes.len()
            );
        }

        let named: std::collections::BTreeSet<&str> =
            cases.iter().map(|(spec, _)| spec.as_str()).collect();
        for (spec, _) in &answers {
            assert!(
                named.contains(spec),
                "the file carries `{spec}`, which no case names"
            );
        }
        assert_eq!(answers.len(), cases.len());
    }

    /// An independent SHA-256, for the differential below to compare against.
    ///
    /// `sha256sum` on a GNU host, `shasum -a 256` on a Mac -- this repository
    /// has seats on both. Both print `<digest>  <path>`, so the caller reads
    /// them the same way.
    ///
    /// Returns the program and the arguments that precede the paths.
    fn an_independent_sha256() -> Option<(&'static str, &'static [&'static str])> {
        for (program, args) in [
            ("sha256sum", &[] as &[&str]),
            ("shasum", &["-a", "256"] as &[&str]),
        ] {
            let answered = std::process::Command::new(program)
                .args(args)
                .arg("--version")
                .output()
                .is_ok_and(|probe| probe.status.success());
            if answered {
                return Some((program, args));
            }
        }
        None
    }

    /// The differential: the ADDITIONAL check, not the portable one.
    ///
    /// A fresh instance ran this by hand while the algorithm was hand-rolled,
    /// as a proof of our arithmetic. Ruling 7 kept it and changed what it is
    /// for: it is now a **conformance check on `sha2`** -- what catches a
    /// version bump that changes behaviour, a feature flag that swaps an
    /// implementation, or a build where the crate is not what the lockfile
    /// says. The published vectors above cannot catch those on their own,
    /// because a wrong implementation that still gets `abc` right is exactly
    /// what a vector set is blind to. That is why both tests exist and why
    /// neither replaces the other.
    ///
    /// **The set is built from named groups and its size is whatever they
    /// come to.** The groups are in `cases`; an early version was very nearly
    /// named for a reviewer's count of 221, which would have meant padding
    /// the set until it reached 221 -- fitting the evidence to the label.
    /// What each group is for is written beside it instead.
    ///
    /// # It has no skip, and that is the whole point
    ///
    /// The first version had THREE early returns -- no temp directory, a
    /// staging write that failed, no `sha256sum` -- each returning a
    /// **passing** test. A review closed one of them and left two, under a
    /// comment claiming the class was handled; `TMPDIR` pointed anywhere
    /// unwritable then retired the entire check, took its own seeded fault
    /// green with it, and let a deliberately corrupted digest through. And
    /// the `eprintln!` those paths announced themselves with is swallowed by
    /// libtest on a passing test, so the log could not tell a run that
    /// differentiated from one that did not.
    ///
    /// So there is no skip at all. **This test declares a host requirement:
    /// an independent SHA-256 must be on `PATH`.** A conformance check that
    /// cannot reach its reference implementation has not been performed, and
    /// a green test that did not perform its check is the failure this whole
    /// module is about. Every seat this repository has -- GNU and Mac -- ships
    /// one of the two programs above.
    #[test]
    fn the_dependency_agrees_with_the_system_on_every_shape_that_breaks_a_sha256() {
        // The same cases the portable test runs, so the two cannot drift
        // into checking different inputs -- and so this run is in a position
        // to say whether the frozen ANSWERS are still right, which it does
        // below.
        let cases = cases();
        let answers = committed(VECTORS);
        let inputs: Vec<Vec<u8>> = cases.iter().map(|(_, bytes)| bytes.clone()).collect();

        let (program, prefix) = an_independent_sha256().expect(
            "this test needs an independent SHA-256 on PATH -- `sha256sum` or \
             `shasum` -- to compare `sha2` against. It does not skip when one is \
             absent: a conformance check that cannot reach its reference \
             implementation has not been performed, and a green test that did \
             not perform its check is the defect this module exists to prevent.",
        );

        // Through FILES rather than a pipe. An earlier version fed hex on
        // stdin and decoded it with `xxd`, which is not on every host -- and
        // its absence did not surface as "the tool is missing", it surfaced
        // as a DIGEST MISMATCH on input 1, which is a red that is not about
        // its own fault.
        let ours: Vec<String> = inputs.iter().map(|bytes| sha256_hex(bytes)).collect();
        // Unique per run, and `create_dir` rather than `create_dir_all` so an
        // existing directory is an error rather than something to write into:
        // a predictable name a local process can pre-create, plus writes that
        // follow symlinks, is CWE-377 even in a test.
        let base = std::env::temp_dir().join(format!(
            "diet-digest-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|since| since.as_nanos())
                .unwrap_or_default()
        ));
        std::fs::create_dir(&base).expect("a temp directory to stage the inputs in");
        let mut paths = Vec::with_capacity(inputs.len());
        for (at, bytes) in inputs.iter().enumerate() {
            let path = base.join(format!("{at:04}.bin"));
            std::fs::write(&path, bytes).expect("the inputs stage");
            paths.push(path);
        }

        let spawned = std::process::Command::new(program)
            .args(prefix)
            .args(&paths)
            .output();
        let _ = std::fs::remove_dir_all(&base);
        let output = spawned.unwrap_or_else(|why| {
            panic!("`{program}` answered a probe and then could not be run: {why}")
        });
        assert!(
            output.status.success(),
            "`{program}` itself failed, which is not a disagreement about a \
             digest: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        let theirs: Vec<String> = String::from_utf8_lossy(&output.stdout)
            .lines()
            .filter_map(|line| line.split_whitespace().next())
            // GNU coreutils escapes a line whose FILENAME contains a
            // backslash or a newline by prefixing the whole line with `\`.
            // A `TMPDIR` with a backslash in it therefore turned every digest
            // into `\e3b0c4...` and reported a mismatch on input 0 -- a red
            // that is not about its own fault, which is the class this module
            // keeps having to close. The digest itself is unaffected.
            .map(|digest| digest.strip_prefix('\\').unwrap_or(digest).to_owned())
            .collect();

        assert_eq!(
            theirs.len(),
            inputs.len(),
            "`{program}` answered for every one of the {} inputs, or this \
             compares two lists that are not aligned",
            inputs.len()
        );
        for (at, (ours, theirs)) in ours.iter().zip(&theirs).enumerate() {
            assert_eq!(
                ours,
                theirs,
                "input {at} ({} bytes) disagrees with `{program}`'s digest",
                inputs[at].len()
            );
        }

        // The differential's second job, and the reason the frozen file is
        // safe to lean on. The loop above proves the DEPENDENCY agrees with
        // an independent implementation; this proves the COMMITTED ANSWERS
        // do. Nothing that reads only `vectors.tsv` can check that, so a
        // vector file nobody rechecks is one that can be wrong in a single
        // direction forever -- and it would take the portable test with it,
        // silently, because the two would agree.
        let held: std::collections::BTreeMap<&str, &str> = answers.iter().copied().collect();
        for (at, ((spec, _), theirs)) in cases.iter().zip(&theirs).enumerate() {
            let frozen = held
                .get(spec.as_str())
                .unwrap_or_else(|| panic!("case {at}: the file has no answer for `{spec}`"));
            assert_eq!(
                frozen, theirs,
                "committed vector {at} (`{spec}`) no longer agrees with `{program}`. \
                 The file is stale or was wrong when it was written; regenerate it \
                 from an independent implementation rather than from `sha2`."
            );
        }
    }

    /// Every fault in this lane's `gate.toml` still names source that is there.
    ///
    /// The digest is its own lane now that it is at the crate root: its
    /// mutations are not the drive's, and a manifest that claimed them would
    /// be naming a file its lane does not own.
    #[test]
    fn every_seeded_fault_still_names_source_that_is_there() {
        crate::gate::every_seeded_fault_still_names_source(
            include_str!("../digest/gate.toml"),
            // One file, because that is the whole lane.
            include_str!("digest.rs"),
            "digest",
        );
    }
}
